# GENERATED by ggen_igniter from priv/ggen/ash-pplan-store-conformance-pack/ontology.ttl.
# Do not edit. Regenerate with bin/manufacture-store-conformance.
defmodule AshPPlan.Test.StoreConformance do
  @moduledoc """
  Store conformance suite, generated from the sc:Law individuals of the store-conformance
  ontology. Each law is a plain function `law_<id>(mod, store)` that raises on violation, so one
  body serves two consumers:

    * `use AshPPlan.Test.StoreConformance, store: Module, start: fun` defines one ExUnit test per
      law against any `AshPPlan.Reactor.Durable.Store` implementation. `start` is a zero-arity
      function returning `{:ok, store}`; a fresh store is started per test and run "r1" is
      pre-inserted.
    * `run/2` executes every law against a store and returns `[{law_id, :ok | {:error, exception}}]`,
      which the anti-vacuity court uses to prove a deliberately broken store fails the suite.

  Anti-vacuity mutation: remove any `sc:covers` link (the template refuses an uncovered
  callback) or weaken a law body, and the corresponding mutant store in the conformance courts
  passes the suite.
  """
  import ExUnit.Assertions

  @t0 ~U[2026-01-01 00:00:00.000Z]

  @callbacks [
    {:checkpoints, 2},
    {:claim, 5},
    {:claim_undo, 4},
    {:consume_signal, 3},
    {:deliver_signal, 4},
    {:get_run, 2},
    {:get_waiter, 3},
    {:list_runs, 1},
    {:park, 6},
    {:pending_signal, 3},
    {:record, 6},
    {:release, 3},
    {:release_all, 2},
    {:release_claim, 3},
    {:release_undo, 3},
    {:signals, 2},
    {:standing, 2},
    {:start_run, 2},
    {:transition, 5},
    {:waiters, 2}
  ]

  @laws [
    %{
      id: "start_run_exclusive",
      statement:
        "start_run is exclusive per id; get_run/list_runs round-trip in insertion order; parent is stored",
      covers: ["get_run", "list_runs", "start_run"]
    },
    %{
      id: "transition_guarded",
      statement:
        "transition applies only from an allowed status: ok bumps version, stale, illegal, not_found; terminal is absorbing",
      covers: ["get_run", "transition"]
    },
    %{
      id: "claim_lease",
      statement:
        "claim is free when unclaimed, lease lapsed, or the same claimer re-enters; a nil claimer never re-enters",
      covers: ["claim", "get_run"]
    },
    %{
      id: "claim_exclusive_concurrent",
      statement: "concurrent claim has exactly one winner",
      covers: ["claim"]
    },
    %{
      id: "release_claim_owner_only",
      statement:
        "release_claim clears only the holder's claim; it is idempotent and a no-op for others",
      covers: ["claim", "get_run", "release_claim"]
    },
    %{
      id: "record_insert_or_adopt",
      statement:
        "record is insert-or-adopt: a second write for (run, key) returns the standing checkpoint unchanged",
      covers: ["checkpoints", "record"]
    },
    %{
      id: "record_concurrent_adopts",
      statement:
        "concurrent record leaves one standing row and every caller sees the first output",
      covers: ["record", "standing"]
    },
    %{
      id: "standing_ordered_by_seq",
      statement:
        "standing lists non-undone checkpoints of one run in seq order; checkpoints are scoped per run",
      covers: ["checkpoints", "record", "standing"]
    },
    %{
      id: "terminal_refuses_checkpoints",
      statement: "a terminal run refuses new checkpoints but still adopts a standing one",
      covers: ["checkpoints", "record", "transition"]
    },
    %{
      id: "undo_once",
      statement:
        "claim_undo is consume-once per checkpoint and removes it from standing; release_undo reopens it",
      covers: ["claim_undo", "release_undo", "standing"]
    },
    %{
      id: "signals_fifo_consume_once",
      statement: "signals are FIFO per name, ids are unique, and consume_signal is consume-once",
      covers: ["consume_signal", "deliver_signal", "pending_signal", "signals"]
    },
    %{
      id: "consume_concurrent",
      statement: "concurrent consume_signal has exactly one winner",
      covers: ["consume_signal"]
    },
    %{
      id: "park_deadline_once",
      statement:
        "park keeps the first deadline (measured once) unless overwrite: true; waiters are listed by name",
      covers: ["get_waiter", "park", "waiters"]
    },
    %{
      id: "release_idempotent",
      statement: "release and release_all are idempotent and scoped to the run",
      covers: ["park", "release", "release_all", "waiters"]
    }
  ]

  @doc "Callbacks (name, arity) declared by the ontology."
  @spec callbacks() :: [{atom(), non_neg_integer()}]
  def callbacks, do: @callbacks

  @doc "Laws (id, statement, covered callbacks) declared by the ontology."
  @spec laws() :: [%{id: String.t(), statement: String.t(), covers: [String.t()]}]
  def laws, do: @laws

  @doc "Fixed clock used by the laws."
  def t0, do: @t0

  @doc "Starts a fresh store via `start` (returning `{:ok, store}`) with run \"r1\" inserted."
  def boot(mod, start) do
    {:ok, s} = start.()
    {:ok, _} = mod.start_run(s, %{id: "r1", model: :m, bindings: %{a: 1}})
    s
  end

  @doc "Runs every law against `mod` on a fresh store each; returns per-law outcomes."
  @spec run(module(), (-> {:ok, term()})) :: [{String.t(), :ok | {:error, Exception.t()}}]
  def run(mod, start) do
    for %{id: id} <- @laws do
      s = boot(mod, start)

      outcome =
        try do
          run_law(id, mod, s)
          :ok
        rescue
          e -> {:error, e}
        catch
          kind, reason -> {:error, %RuntimeError{message: "#{kind}: #{inspect(reason)}"}}
        after
          if is_pid(s) and Process.alive?(s), do: GenServer.stop(s, :normal)
        end

      {id, outcome}
    end
  end

  @doc "Dispatches one law by id."
  def run_law("start_run_exclusive", mod, s), do: law_start_run_exclusive(mod, s)
  def run_law("transition_guarded", mod, s), do: law_transition_guarded(mod, s)
  def run_law("claim_lease", mod, s), do: law_claim_lease(mod, s)
  def run_law("claim_exclusive_concurrent", mod, s), do: law_claim_exclusive_concurrent(mod, s)
  def run_law("release_claim_owner_only", mod, s), do: law_release_claim_owner_only(mod, s)
  def run_law("record_insert_or_adopt", mod, s), do: law_record_insert_or_adopt(mod, s)
  def run_law("record_concurrent_adopts", mod, s), do: law_record_concurrent_adopts(mod, s)
  def run_law("standing_ordered_by_seq", mod, s), do: law_standing_ordered_by_seq(mod, s)

  def run_law("terminal_refuses_checkpoints", mod, s),
    do: law_terminal_refuses_checkpoints(mod, s)

  def run_law("undo_once", mod, s), do: law_undo_once(mod, s)
  def run_law("signals_fifo_consume_once", mod, s), do: law_signals_fifo_consume_once(mod, s)
  def run_law("consume_concurrent", mod, s), do: law_consume_concurrent(mod, s)
  def run_law("park_deadline_once", mod, s), do: law_park_deadline_once(mod, s)
  def run_law("release_idempotent", mod, s), do: law_release_idempotent(mod, s)

  @doc "start_run is exclusive per id; get_run/list_runs round-trip in insertion order; parent is stored"
  def law_start_run_exclusive(mod, s) do
    assert {:error, :exists} = mod.start_run(s, %{id: "r1"})
    {:ok, c} = mod.start_run(s, %{id: "r2", parent: {"r1", "sig"}})
    assert c.parent_id == "r1" and c.parent_signal == "sig"
    assert c.status == :pending and c.version == 1
    assert mod.get_run(s, "r1").bindings == %{a: 1}
    assert mod.get_run(s, "nope") == nil
    assert Enum.map(mod.list_runs(s), & &1.id) == ["r1", "r2"]
  end

  @doc "transition applies only from an allowed status: ok bumps version, stale, illegal, not_found; terminal is absorbing"
  def law_transition_guarded(mod, s) do
    v = mod.get_run(s, "r1").version
    assert {:ok, r} = mod.transition(s, "r1", [:pending], :waiting, %{})
    assert r.status == :waiting and r.version == v + 1
    assert {:error, :stale} = mod.transition(s, "r1", [:pending], :completed, %{})
    assert {:error, :illegal} = mod.transition(s, "r1", :any, :cancelled, %{})
    assert {:error, :not_found} = mod.transition(s, "zz", :any, :failed, %{})
    assert {:ok, %{result: 42}} = mod.transition(s, "r1", :any, :completed, %{result: 42})
    assert {:error, :stale} = mod.transition(s, "r1", :any, :failed, %{})
    assert mod.get_run(s, "r1").status == :completed
    assert mod.get_run(s, "r1").result == 42
  end

  @doc "claim is free when unclaimed, lease lapsed, or the same claimer re-enters; a nil claimer never re-enters"
  def law_claim_lease(mod, s) do
    t0 = @t0
    assert {:ok, r} = mod.claim(s, "r1", :a, 1000, t0)
    assert r.claimed_by == :a
    assert :taken = mod.claim(s, "r1", :b, 1000, DateTime.add(t0, 500, :millisecond))
    assert {:ok, _} = mod.claim(s, "r1", :a, 1000, DateTime.add(t0, 500, :millisecond))
    assert {:ok, r} = mod.claim(s, "r1", :b, 1000, DateTime.add(t0, 5000, :millisecond))
    assert r.claimed_by == :b
    assert {:ok, _} = mod.claim(s, "r1", nil, 1000, DateTime.add(t0, 20_000, :millisecond))
    assert :taken = mod.claim(s, "r1", nil, 1000, DateTime.add(t0, 20_001, :millisecond))
    assert {:ok, _} = mod.claim(s, "r1", nil, 1000, DateTime.add(t0, 21_000, :millisecond))
    assert :taken = mod.claim(s, "missing", :a, 10, t0)
  end

  @doc "concurrent claim has exactly one winner"
  def law_claim_exclusive_concurrent(mod, s) do
    t0 = @t0

    results =
      1..32
      |> Task.async_stream(fn n -> mod.claim(s, "r1", {:c, n}, 60_000, t0) end,
        max_concurrency: 32
      )
      |> Enum.map(fn {:ok, r} -> r end)

    assert Enum.count(results, &match?({:ok, _}, &1)) == 1
    assert Enum.count(results, &(&1 == :taken)) == 31
  end

  @doc "release_claim clears only the holder's claim; it is idempotent and a no-op for others"
  def law_release_claim_owner_only(mod, s) do
    t0 = @t0
    assert {:ok, _} = mod.claim(s, "r1", :a, 60_000, t0)
    assert :ok = mod.release_claim(s, "r1", :b)
    assert mod.get_run(s, "r1").claimed_by == :a
    assert :ok = mod.release_claim(s, "r1", :a)
    assert mod.get_run(s, "r1").claimed_by == nil
    assert :ok = mod.release_claim(s, "r1", :a)
    assert :ok = mod.release_claim(s, "missing", :a)
    assert {:ok, _} = mod.claim(s, "r1", :b, 60_000, t0)
  end

  @doc "record is insert-or-adopt: a second write for (run, key) returns the standing checkpoint unchanged"
  def law_record_insert_or_adopt(mod, s) do
    {:ok, a} = mod.record(s, "r1", "k1", "one", 1, %{impl: Foo, args: %{x: 1}})
    {:ok, b} = mod.record(s, "r1", "k2", "two", 2, %{})
    {:ok, a2} = mod.record(s, "r1", "k1", "one", 999, %{})
    assert a2 == a and a2.output == 1 and a.impl == Foo and a.args == %{x: 1}
    assert b.seq > a.seq
    assert Map.keys(mod.checkpoints(s, "r1")) |> Enum.sort() == ["k1", "k2"]
    assert mod.checkpoints(s, "r1")["k1"].output == 1
  end

  @doc "concurrent record leaves one standing row and every caller sees the first output"
  def law_record_concurrent_adopts(mod, s) do
    outs =
      1..24
      |> Task.async_stream(fn n -> mod.record(s, "r1", "k", "l", n, %{}) end, max_concurrency: 24)
      |> Enum.map(fn {:ok, {:ok, cp}} -> cp.output end)

    assert length(Enum.uniq(outs)) == 1
    assert length(mod.standing(s, "r1")) == 1
  end

  @doc "standing lists non-undone checkpoints of one run in seq order; checkpoints are scoped per run"
  def law_standing_ordered_by_seq(mod, s) do
    {:ok, _} = mod.start_run(s, %{id: "r2"})
    {:ok, a} = mod.record(s, "r1", "z", "first", 1, %{})
    {:ok, _} = mod.record(s, "r2", "x", "other", 0, %{})
    {:ok, b} = mod.record(s, "r1", "a", "second", 2, %{})
    {:ok, c} = mod.record(s, "r1", "m", "third", 3, %{})
    assert a.seq < b.seq and b.seq < c.seq
    assert Enum.map(mod.standing(s, "r1"), & &1.label) == ["first", "second", "third"]
    assert Enum.map(mod.standing(s, "r2"), & &1.label) == ["other"]
    assert mod.standing(s, "none") == []
    assert mod.checkpoints(s, "none") == %{}
  end

  @doc "a terminal run refuses new checkpoints but still adopts a standing one"
  def law_terminal_refuses_checkpoints(mod, s) do
    {:ok, a} = mod.record(s, "r1", "k1", "one", 1, %{})
    {:ok, _} = mod.transition(s, "r1", :any, :completed, %{})
    assert {:error, :terminal} = mod.record(s, "r1", "k2", "two", 2, %{})
    assert {:ok, again} = mod.record(s, "r1", "k1", "one", 999, %{})
    assert again == a
    assert Map.keys(mod.checkpoints(s, "r1")) == ["k1"]
  end

  @doc "claim_undo is consume-once per checkpoint and removes it from standing; release_undo reopens it"
  def law_undo_once(mod, s) do
    t0 = @t0
    {:ok, _} = mod.record(s, "r1", "k", "l", 1, %{})
    assert {:ok, cp} = mod.claim_undo(s, "r1", "k", t0)
    assert cp.undone_at == t0
    assert :taken = mod.claim_undo(s, "r1", "k", t0)
    assert mod.standing(s, "r1") == []
    assert :ok = mod.release_undo(s, "r1", "k")
    assert Enum.map(mod.standing(s, "r1"), & &1.step_key) == ["k"]
    assert {:ok, _} = mod.claim_undo(s, "r1", "k", t0)
    assert :taken = mod.claim_undo(s, "r1", "nokey", t0)
    assert :ok = mod.release_undo(s, "r1", "nokey")
  end

  @doc "signals are FIFO per name, ids are unique, and consume_signal is consume-once"
  def law_signals_fifo_consume_once(mod, s) do
    t0 = @t0
    {:ok, s1} = mod.deliver_signal(s, "r1", "go", 1)
    {:ok, s2} = mod.deliver_signal(s, "r1", "go", 2)
    {:ok, _} = mod.deliver_signal(s, "r1", "other", 3)
    assert s1.id != s2.id
    assert mod.pending_signal(s, "r1", "go").id == s1.id
    assert mod.pending_signal(s, "r1", "none") == nil
    assert {:ok, consumed} = mod.consume_signal(s, s1.id, t0)
    assert consumed.consumed_at == t0
    assert :taken = mod.consume_signal(s, s1.id, t0)
    assert :taken = mod.consume_signal(s, :missing, t0)
    assert mod.pending_signal(s, "r1", "go").id == s2.id
    assert length(mod.signals(s, "r1")) == 3
    assert Enum.map(mod.signals(s, "r1"), & &1.payload) == [1, 2, 3]
    assert mod.signals(s, "r2") == []
  end

  @doc "concurrent consume_signal has exactly one winner"
  def law_consume_concurrent(mod, s) do
    t0 = @t0
    {:ok, sig} = mod.deliver_signal(s, "r1", "go", 1)

    results =
      1..16
      |> Task.async_stream(fn _ -> mod.consume_signal(s, sig.id, t0) end, max_concurrency: 16)
      |> Enum.map(fn {:ok, r} -> r end)

    assert Enum.count(results, &match?({:ok, _}, &1)) == 1
    assert Enum.count(results, &(&1 == :taken)) == 15
    assert mod.pending_signal(s, "r1", "go") == nil
  end

  @doc "park keeps the first deadline (measured once) unless overwrite: true; waiters are listed by name"
  def law_park_deadline_once(mod, s) do
    t0 = @t0
    d1 = DateTime.add(t0, 1000, :millisecond)
    d2 = DateTime.add(t0, 9000, :millisecond)
    assert {:ok, w} = mod.park(s, "r1", "w", :signal, d1, [])
    assert {:ok, ^w} = mod.park(s, "r1", "w", :signal, d2, [])
    assert mod.get_waiter(s, "r1", "w").deadline == d1
    assert {:ok, w2} = mod.park(s, "r1", "w", :poll, d2, overwrite: true)
    assert w2.deadline == d2 and w2.kind == :poll
    assert mod.get_waiter(s, "r1", "w").deadline == d2
    {:ok, _} = mod.park(s, "r1", "v", :signal, nil, [])
    assert Enum.map(mod.waiters(s, "r1"), & &1.name) == ["v", "w"]
    assert mod.get_waiter(s, "r1", "absent") == nil
    assert mod.waiters(s, "r2") == []
  end

  @doc "release and release_all are idempotent and scoped to the run"
  def law_release_idempotent(mod, s) do
    {:ok, _} = mod.start_run(s, %{id: "r2"})
    {:ok, _} = mod.park(s, "r1", "w", :signal, nil, [])
    {:ok, _} = mod.park(s, "r1", "v", :signal, nil, [])
    {:ok, _} = mod.park(s, "r2", "w", :signal, nil, [])
    assert :ok = mod.release(s, "r1", "w")
    assert :ok = mod.release(s, "r1", "w")
    assert mod.get_waiter(s, "r1", "w") == nil
    assert mod.get_waiter(s, "r2", "w") != nil
    assert :ok = mod.release_all(s, "r1")
    assert :ok = mod.release_all(s, "r1")
    assert mod.waiters(s, "r1") == []
    assert length(mod.waiters(s, "r2")) == 1
  end

  defmacro __using__(opts) do
    store = Keyword.fetch!(opts, :store)
    start = Keyword.fetch!(opts, :start)
    case_opts = Keyword.get(opts, :case, async: true)

    tests =
      for %{id: id, statement: statement} <- @laws do
        quote do
          test unquote("#{id}: #{statement}"), %{conformance_store: s} do
            apply(AshPPlan.Test.StoreConformance, unquote(String.to_atom("law_" <> id)), [
              unquote(store),
              s
            ])
          end
        end
      end

    quote do
      use ExUnit.Case, unquote(case_opts)

      setup do
        %{conformance_store: AshPPlan.Test.StoreConformance.boot(unquote(store), unquote(start))}
      end

      unquote_splicing(tests)
    end
  end
end
