
// GENERATED by ggen_igniter from priv/ggen/ash-pplan-durable-tla-pack/ontology.ttl.
// Do not edit. Regenerate with ./bin/manufacture-durable-tla.
//
// Stateright differential-check model of the durable claim/lease, attempt, park, signal,
// wake, cancel/unwind protocol — generated from the SAME protocol ontology as
// priv/tla/durable/DurableProtocol.tla, so a verdict disagreement between checkers is a
// court failure, not a modeling drift.
//
// Differential contract (mirrors test/durable/native_tla_court_test.exs):
//   - protocol model: admitted (NoLostWakeup leads-to property + invariant core)
//   - guard-dropped mutants claim_free / run_held / record_once: counterexample expected
//
// Build (scratch dir only, never packaged):
//   cargo new --lib stateright-diff && cargo add stateright@0.18 \
//     && cp priv/tla/durable/stateright/model.rs src/lib.rs
//   cargo test
#![allow(dead_code)]

/// Protocol states, straight from the ontology (`dp:s_*` individuals).
pub const STATUSES: &[&str] = &[
    "cancelled",
    "cancelling",
    "completed",
    "failed",
    "pending",
    "polling",
    "unwind_blocked",
    "unwinding",
    "waiting",
];

/// Terminal states (`dp:terminal true`).
pub const TERMINAL: &[&str] = &[
    "cancelled",
    "completed",
    "failed",
];

/// Parked states (fixed by the protocol: waiting, polling).
pub const PARKED: &[&str] = &[
    "waiting",
    "polling",
];

/// Forward states (fixed by the protocol: pending, waiting, polling).
pub const FORWARD: &[&str] = &[
    "pending",
    "waiting",
    "polling",
];

/// Protocol actions (`dp:a_*` individuals).
pub const ACTIONS: &[&str] = &[
    "Cancel",
    "Claim",
    "Complete",
    "Deliver",
    "Park",
    "RecordA",
    "RecordB",
    "Release",
    "Rollback",
];

/// Guards per action, in `gorder` (`dp:g_*` individuals).
pub const GUARDS: &[(&str, &[&str])] = &[
    ("Cancel", &[
        "cancel_from",
    ]),
    ("Claim", &[
        "claim_nonterminal",
        "claim_free",
        "claim_idle",
    ]),
    ("Complete", &[
        "run_held",
        "settle_from",
        "all_recorded",
    ]),
    ("Deliver", &[
        "deliver_once",
    ]),
    ("Park", &[
        "run_held",
        "settle_from",
        "parks_on_await",
    ]),
    ("RecordA", &[
        "run_held",
        "run_forward",
        "record_once",
    ]),
    ("RecordB", &[
        "run_held",
        "run_forward",
        "await_after_a",
        "signal_available",
        "record_once",
    ]),
    ("Release", &[
        "run_held",
        "ended_terminal",
    ]),
    ("Rollback", &[
        "run_held",
        "rollback_from",
    ]),
];

/// Properties the differential court must agree on with tla-rs
/// (`dp:p_*` individuals: ClaimExclusive, NoDoubleEffect, NoLostWakeup, ...).
pub const PROPERTIES: &[&str] = &[
    "TypeOK",
    "ClaimExclusive",
    "NoDoubleEffect",
    "TerminalAbsorbing",
    "CancelNeverOverwritten",
    "NoLostWakeup",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn protocol_vocabulary_matches_ontology() {
        assert!(STATUSES.contains(&"pending"));
        assert!(TERMINAL.contains(&"completed"));
        assert!(PROPERTIES.contains(&"NoLostWakeup"));
    }
}
