# GENERATED by ggen_igniter from priv/ggen/ash-pplan-standing-pack/ontology.ttl.
# Do not edit. Regenerate with bin/manufacture-standing.
# Adapted from ggen-marketplace evidence-standing-pack templates/chain.ex.tmpl.
defmodule AshPPlan.Standing.Chain do
  @moduledoc """
  Hash-chained, append-only ledger digest for a standing run: every action has a pending entry
  and exactly one outcome entry (no outcome without a pending, no standing on a pending), the
  chain is sealed once, and `verify/1` recomputes every hash. The digest of a run is the hash of
  its seal entry, so any edit to a ledger entry changes the receipt's replay digest.
  Algorithm, genesis, canonical fields, phases and standing values come from the standing ontology.
  """

  @algorithm "sha256"
  @genesis "0000000000000000000000000000000000000000000000000000000000000000"
  @fields [
    "entry_id",
    "parent_hash",
    "phase",
    "standing",
    "subject",
    "action",
    "pending_ref",
    "seal"
  ]
  @phases ["pending", "outcome"]
  @standings [
    "ALIVE",
    "BLOCKED",
    "BUILD_BROKEN",
    "PARTIAL_ALIVE",
    "REFUSED",
    "UNKNOWN",
    "UNSUPPORTED"
  ]
  @neutral "UNKNOWN"
  @pending List.first(@phases)
  @outcome List.last(@phases)

  @type entry :: map()
  @type chain :: [entry()]

  def algorithm, do: @algorithm
  def genesis, do: @genesis

  @doc "Lowercase hex digest of `text` under the policy algorithm."
  def digest(text) do
    case @algorithm do
      "sha256" -> :crypto.hash(:sha256, text) |> Base.encode16(case: :lower)
      "sha512" -> :crypto.hash(:sha512, text) |> Base.encode16(case: :lower)
      other -> raise ArgumentError, "unsupported algorithm #{other}"
    end
  end

  @doc "Canonical text of an entry: policy fields in order, one `name=value` per line."
  def canonical(e) do
    Enum.map_join(@fields, "\n", fn f ->
      v = e |> Map.fetch!(String.to_atom(f)) |> to_string()
      if String.contains?(v, "\n"), do: raise(ArgumentError, "LF in field #{f}")
      f <> "=" <> v
    end)
  end

  defp make(chain, id, phase, standing, subject, action, seal, pending_ref \\ "") do
    unless phase in @phases and standing in @standings,
      do: raise(ArgumentError, "bad phase/standing")

    parent =
      case List.last(chain) do
        nil -> @genesis
        p -> p.hash
      end

    e = %{
      entry_id: id,
      parent_hash: parent,
      phase: phase,
      standing: standing,
      subject: subject,
      action: action,
      pending_ref: pending_ref,
      seal: seal
    }

    Map.put(e, :hash, digest(canonical(e)))
  end

  def sealed?(chain), do: Enum.any?(chain, & &1.seal)

  defp paired?(chain, hash),
    do: Enum.any?(chain, &(&1.phase == @outcome and &1.pending_ref == hash))

  @doc "entry_ids of pending entries no outcome has closed yet."
  def unpaired(chain),
    do: for(e <- chain, e.phase == @pending, not paired?(chain, e.hash), do: e.entry_id)

  @spec append_pending(chain(), String.t(), String.t(), String.t()) ::
          {:ok, chain()} | {:error, atom()}
  def append_pending(chain, id, subject, action) do
    if sealed?(chain),
      do: {:error, :sealed},
      else: {:ok, chain ++ [make(chain, id, @pending, @neutral, subject, action, false)]}
  end

  @spec append_outcome(chain(), String.t(), String.t(), String.t(), String.t()) ::
          {:ok, chain()} | {:error, atom()}
  def append_outcome(chain, id, standing, subject, action) do
    open =
      Enum.find(
        chain,
        &(&1.phase == @pending and &1.action == action and not paired?(chain, &1.hash))
      )

    cond do
      sealed?(chain) ->
        {:error, :sealed}

      standing not in @standings ->
        {:error, :bad_phase_or_standing}

      open == nil ->
        {:error, :outcome_without_pending}

      true ->
        {:ok, chain ++ [make(chain, id, @outcome, standing, subject, action, false, open.hash)]}
    end
  end

  @spec seal(chain(), String.t(), String.t(), String.t()) :: {:ok, chain()} | {:error, atom()}
  def seal(chain, id, standing, subject) do
    cond do
      sealed?(chain) -> {:error, :already_sealed}
      standing not in @standings -> {:error, :bad_phase_or_standing}
      unpaired(chain) != [] -> {:error, :unpaired_pending}
      true -> {:ok, chain ++ [make(chain, id, @outcome, standing, subject, "seal", true)]}
    end
  end

  @doc "Recompute every hash and the pending/outcome/seal discipline."
  @spec verify(chain()) :: boolean()
  def verify(chain) do
    {ok, _, _, _} =
      Enum.reduce(chain, {true, @genesis, %{}, MapSet.new()}, fn e, {ok, prev, seen, used} ->
        base = ok and e.parent_hash == prev and e.hash == digest(canonical(e))

        {good, seen, used} =
          cond do
            e.phase == @pending ->
              {e.standing == @neutral and e.pending_ref == "", Map.put(seen, e.hash, e), used}

            e.seal ->
              {e.pending_ref == "" and Enum.all?(Map.keys(seen), &MapSet.member?(used, &1)), seen,
               used}

            true ->
              p = Map.get(seen, e.pending_ref)

              {p != nil and p.action == e.action and not MapSet.member?(used, e.pending_ref),
               seen, MapSet.put(used, e.pending_ref)}
          end

        {base and good, e.hash, seen, used}
      end)

    seals = Enum.count(chain, & &1.seal)
    ok and seals <= 1 and (seals == 0 or List.last(chain).seal)
  end

  @doc "Hash of the last entry (the seal for a sealed chain), or the genesis for an empty chain."
  def head([]), do: @genesis
  def head(chain), do: List.last(chain).hash
end
