# GENERATED by ggen_igniter from ontology.ttl (Spark DSL extension row ap:dslSection).
# Do not edit. Regenerate with priv/ggen/ash-pplan-dsl-pack/bin/manufacture-dsl.
defmodule AshPPlan.Dsl.PPlan.Lift do
  @moduledoc """
  GENERATED compile-time transformer. Lifts entities and section opts declared
  in the generated `pplan` section into the hand-written `[:workflow]`
  section, so every existing verifier and `GenerateModel` apply unchanged.
  """
  use Spark.Dsl.Transformer

  alias Spark.Dsl.Transformer

  # Spark sorts transformers by before?/after? hooks, not declaration order:
  # lift BEFORE GenerateModel reads the merged [:workflow] section.
  @impl true
  def before?(AshPPlan.Workflow.Dsl.Transformers.GenerateModel), do: true
  def before?(_), do: false

  @impl true
  def transform(dsl_state) do
    dsl_state =
      dsl_state
      |> lift_entities()
      |> lift_opts()

    {:ok, dsl_state}
  end

  defp lift_entities(dsl_state) do
    dsl_state
    |> Transformer.get_entities([:pplan])
    |> Enum.reverse()
    |> Enum.reduce(dsl_state, fn entity, dsl_state ->
      Transformer.add_entity(dsl_state, [:workflow], entity, type: :append)
    end)
  end

  defp lift_opts(dsl_state) do
    dsl_state
    |> Map.get([:pplan])
    |> case do
      nil ->
        dsl_state

      config ->
        Enum.reduce(config.opts || [], dsl_state, fn {key, value}, dsl_state ->
          Transformer.set_option(dsl_state, [:workflow], key, value)
        end)
    end
  end
end
