defmodule AshPPlan.Courts.PackProtocolCourtTest do
  @moduledoc """
  Pack court for the vendored `ash-pplan-protocol-court-pack`
  (`priv/ggen/vendor/ash-pplan-protocol-court-pack/`), following the
  `pack_chaos_court_test.exs` pattern (real ggen_igniter sync runs).

    1. RENDER — the 4 differential-court surfaces (`protocol.tla.eex`,
       `protocol.cfg.eex`, `stateright_model.rs.eex`, `transitions.exs.eex`)
       render via a real `mix ggen_igniter.sync` into a run-unique scratch
       under `tmp/` and mirror the checked-in
       `priv/ggen/generated/protocol-court/` bytes exactly.
    2. DETERMINISM — a second full render is byte-identical.
    3. GATES — all 7 gates fire with exact row counts
       (1 / 9 / 29 / 9 / 23 / 6 / 2) via `GgenIgniter.Query.Oxigraph`.
    4. ANTI-VACUITY — a corrupt copy of the pack (one `pcp:State` individual
       stripped of its class membership) provably changes the outputs:
       gate 020 drops to 8 rows and the re-rendered `.tla` differs from the
       baseline. A court that admits its own corruption is vacuous.

  Select-only court: no DO authority.
  """

  use ExUnit.Case, async: false

  @repo Path.expand("../..", __DIR__)
  @pack "priv/ggen/vendor/ash-pplan-protocol-court-pack"
  @generated "priv/ggen/generated/protocol-court"

  @templates %{
    "JobLeaseProtocol.tla" => "templates/protocol.tla.eex",
    "JobLeaseProtocol.cfg" => "templates/protocol.cfg.eex",
    "stateright/model.rs" => "templates/stateright_model.rs.eex",
    "JobLeaseProtocol_transitions.exs" => "templates/transitions.exs.eex"
  }

  @gates [
    {"gates/010_protocols.rq", 1},
    {"gates/020_statuses.rq", 9},
    {"gates/030_transitions.rq", 29},
    {"gates/040_actions.rq", 9},
    {"gates/050_guards.rq", 23},
    {"gates/060_properties.rq", 6},
    {"gates/070_mutants.rq", 2}
  ]

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  defp scratch(name) do
    dir =
      Path.join(@repo, "tmp/court-5courts-proto-#{name}-#{System.unique_integer([:positive])}")

    File.mkdir_p!(dir)

    ExUnit.Callbacks.on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  defp sync(pack_dir, template_rel, out_path) do
    File.mkdir_p!(Path.dirname(out_path))

    args = [
      "ggen_igniter.sync",
      "--pack-dir",
      pack_dir,
      "--template",
      template_rel,
      "--out",
      out_path
    ]

    case System.cmd("mix", args, cd: @repo, stderr_to_stdout: true) do
      {out, 0} -> out
      {out, code} -> flunk("mix #{Enum.join(args, " ")} exited #{code}:\n#{out}")
    end
  end

  defp render_dir(name, pack_dir \\ nil) do
    dir = scratch(name)
    pack = pack_dir || Path.join(@repo, @pack)

    for {out_rel, template} <- @templates do
      sync(pack, Path.join(pack, template), Path.join(dir, out_rel))
    end

    dir
  end

  defp snapshot(dir) do
    @templates
    |> Map.new(fn {out_rel, _} -> {out_rel, File.read!(Path.join(dir, out_rel))} end)
  end

  defp parse_check!(path) do
    case Code.string_to_quoted(File.read!(path)) do
      {:ok, ast} ->
        ast

      {:error, reason} ->
        flunk("rendered file does not parse as Elixir: #{path}\n#{inspect(reason)}")
    end
  end

  defp ontology_graph(pack_dir), do: RDF.Turtle.read_file!(Path.join(pack_dir, "ontology.ttl"))

  defp gate_rows(graph, gate_rel, pack_dir \\ nil) do
    path =
      if pack_dir, do: Path.join(pack_dir, gate_rel), else: Path.join([@repo, @pack, gate_rel])

    length(GgenIgniter.Query.Oxigraph.run(graph, File.read!(path)))
  end

  # ---------------------------------------------------------------------------
  # Court 1: render + byte-identity with the checked-in generated surfaces
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "render: 4 surfaces, non-empty, byte-identical to priv/ggen/generated/protocol-court/" do
    dir = render_dir("render")

    for {out_rel, _} <- @templates do
      content = File.read!(Path.join(dir, out_rel))
      assert content != "" and String.trim(content) != "", "empty render: #{out_rel}"
      assert content =~ "GENERATED by ggen_igniter", "missing provenance header: #{out_rel}"
    end

    assert parse_check!(Path.join(dir, "JobLeaseProtocol_transitions.exs"))

    for {out_rel, _} <- @templates do
      checked_in = Path.join([@repo, @generated, out_rel])
      assert File.regular?(checked_in), "missing checked-in surface: #{out_rel}"

      assert File.read!(Path.join(dir, out_rel)) == File.read!(checked_in),
             "rendered #{out_rel} diverged from #{Path.relative_to(checked_in, @repo)}"
    end
  end

  # ---------------------------------------------------------------------------
  # Court 2: determinism
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "determinism: two independent full renders are byte-identical" do
    a = snapshot(render_dir("render-a"))
    b = snapshot(render_dir("render-b"))

    assert map_size(a) == 4
    assert a == b, "two renders of the same pack diverged — generation is not deterministic"
  end

  # ---------------------------------------------------------------------------
  # Court 3: gates (read-only, exact row counts)
  # ---------------------------------------------------------------------------

  test "gates: all 7 fire with exact row counts via oxigraph" do
    graph = ontology_graph(Path.join(@repo, @pack))

    for {gate, expected} <- @gates do
      rows = gate_rows(graph, gate)
      assert rows == expected, "gate #{gate}: expected #{expected} rows, got #{rows}"
    end
  end

  # ---------------------------------------------------------------------------
  # Court 4: anti-vacuity mutation (tmp pack copy only)
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "anti-vacuity: corrupting one State in a tmp pack copy changes gate + render output" do
    baseline = snapshot(render_dir("mutation-baseline"))

    corrupt = scratch("mutation-corrupt-pack")
    corrupt_pack = Path.join(corrupt, "pack")
    File.cp_r!(Path.join(@repo, @pack), corrupt_pack)

    ontology_path = Path.join(corrupt_pack, "ontology.ttl")
    ttl = File.read!(ontology_path)
    needle = "pcp:s_completed a pcp:State ;"

    assert ttl =~ needle, "corruption target triple not found in pack ontology"

    corrupted = String.replace(ttl, needle, "pcp:s_completed a pcp:NotAState ;", count: 1)
    assert corrupted != ttl, "corruption changed nothing"
    File.write!(ontology_path, corrupted)

    # (a) GATE SENSITIVITY: 020_statuses drops 9 -> 8 on the corrupted graph.
    graph = ontology_graph(corrupt_pack)

    assert gate_rows(graph, "gates/020_statuses.rq", corrupt_pack) == 8,
           "gate 020_statuses did not see the corruption (vacuous)"

    # (b) RENDER SENSITIVITY: re-render from the corrupted pack copy; the .tla
    # surface must differ from the baseline (the completed state left the model).
    sync(
      corrupt_pack,
      Path.join(corrupt_pack, "templates/protocol.tla.eex"),
      Path.join(corrupt, "JobLeaseProtocol.tla")
    )

    mutated_tla = File.read!(Path.join(corrupt, "JobLeaseProtocol.tla"))

    refute mutated_tla == Map.fetch!(baseline, "JobLeaseProtocol.tla"),
           "corrupted render still produced the pristine .tla (render is vacuous)"
  end
end
