defmodule AshPPlan.Courts.PackWorkflowGatesCourtTest do
  @moduledoc """
  Pack court for `priv/ggen/ash-pplan-workflow-pack/`, the only registered
  pack whose gates never execute in-tree. Follows the
  `pack_protocol_court_test.exs` pattern: real ggen_igniter sync runs and
  real Oxigraph query runs.

  Courts:

    1. RENDER - the pack's 10 .eex templates render via real
       `mix ggen_igniter.sync` into a run-unique scratch under `tmp/`
       (ggen_igniter refuses targets outside the project root, so scratch
       must live in-repo; on_exit deletes it). 9 of 10 render standalone
       (38 files: 4 single-output + 30 for_each fan-out); hddl_file.hddl.eex
       is typed-excluded (its EEx calls test-only modules, see
       @excluded_templates). Every surface is non-empty and carries the
       "GENERATED by ggen_igniter" provenance header.

    2. DETERMINISM - a second full render is byte-identical.

    3. GATES - all 15 gates run via `GgenIgniter.Query.Oxigraph` against the
       pack ontology with exact measured row counts. 14 are witness gates
       that must fire (>= 1 row); gate `110_methods` honestly reports 0 rows
       because its `ap:Method` individuals ship in the workflow witness
       corpus (`planning/examples`), not in the pack ontology - a typed,
       documented 0-row witness finding, cross-checked by its companion
       `verify/110_methods.unbound.rq` (offender-reporting: 0 = clean).

    4. OFFENDERS - every `verify/*.unbound.rq` companion must be clean
       (0 rows) on the pristine pack ontology, per
       docs/jira/ECO-GATE-CONVENTION-DECISION.md.

    5. ANTI-VACUITY - a corrupt pack copy (one `ap:Capability` individual
       stripped of its class membership) provably changes both outputs:
       gate 010 drops 31 -> 30 and the re-rendered capability catalog
       differs from the baseline. A court that admits its own corruption
       is vacuous.

  ENGINE-LIMIT caveat (sparql.ex 0.3.12): none of the 15 shipped gates uses
  `EXISTS` today, so the court exercises no EXISTS path. If a future gate in
  this pack crashes on the sparql.ex 0.3.12 EXISTS limitation, record a typed
  ENGINE-LIMIT finding for that gate instead of failing the court; do not
  delete the gate or weaken its siblings.

  Select-only court: no DO authority.
  """

  use ExUnit.Case, async: false

  @repo Path.expand("../..", __DIR__)
  @pack "priv/ggen/ash-pplan-workflow-pack"

  # Render recipe, one entry per pack template. `{template, for_each, out_pattern}`
  # where out_pattern may embed the for_each binding variable. Single-output
  # templates pass nil for_each. Probed standalone against ggen_igniter 26.10.2
  # (2026-10-04).
  @render_recipes [
    {"capability_catalog.ex.eex", nil, "capability_catalog.ex"},
    {"provider_index.ex.eex", nil, "provider_index.ex"},
    {"reactors.ex.eex", nil, "reactors.ex"},
    {"status_fsm.ex.eex", nil, "status_fsm.ex"},
    {"provider.ex.eex", "providers", "<%= provider_id %>.ex"},
    {"court_provider.exs.eex", "providers", "<%= provider_id %>_court.exs"},
    {"court_workflow.exs.eex", "workflows", "court_workflow-<%= name %>.exs"},
    {"runner.ex.eex", "workflows", "runner-<%= name %>.ex"},
    {"workflow.ex.eex", "workflows", "workflow-<%= name %>.ex"}
  ]

  # Typed EXCLUDED-TEMPLATE finding (not a failure): hddl_file.hddl.eex is the
  # one template that cannot render standalone — its EEx body calls the
  # test-only modules `AshPPlan.Examples.Workflows.*.hddl/0`
  # (test/support/examples/workflows/*.ex), unavailable to a plain
  # `mix ggen_igniter.sync` subprocess (:dev compile, test/support not loaded):
  #   UndefinedFunctionError AshPPlan.Examples.Workflows.Activation.hddl/0
  # It renders only through bin/manufacture-examples under mix test env.
  @excluded_templates ["hddl_file.hddl.eex"]

  @templates File.ls!(Path.join(@repo, @pack <> "/templates"))
             |> Enum.filter(&String.ends_with?(&1, ".eex"))

  # Measured empirically via `mix run` + GgenIgniter.Query.Oxigraph against
  # priv/ggen/ash-pplan-workflow-pack/ontology.ttl (2026-10-04).
  @gates [
    {"gates/010_capabilities.rq", 31},
    {"gates/020_providers.rq", 11},
    {"gates/030_provider_caps.rq", 31},
    {"gates/040_provider_props.rq", 14},
    {"gates/050_provider_evidence.rq", 11},
    {"gates/060_workflows.rq", 4},
    {"gates/070_tasks.rq", 15},
    {"gates/080_task_deps.rq", 14},
    {"gates/090_task_outcomes.rq", 16},
    {"gates/100_task_props.rq", 18},
    {"gates/110_methods.rq", 0},
    {"gates/120_reactor_workflows.rq", 4},
    {"gates/121_reactor_tasks.rq", 15},
    {"gates/122_reactor_args.rq", 15},
    {"gates/123_reactor_surface.rq", 4}
  ]

  @offender_gates Path.wildcard(Path.join(@repo, @pack <> "/verify/*.unbound.rq"))
                  |> Enum.map(&Path.relative_to(&1, Path.join(@repo, @pack)))

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  defp scratch(name) do
    dir =
      Path.join(
        @repo,
        "tmp/court-e1-workflow-gates-#{name}-#{System.unique_integer([:positive])}"
      )

    File.mkdir_p!(dir)
    ExUnit.Callbacks.on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  defp sync(pack_dir, template_path, out_path, for_each \\ nil) do
    File.mkdir_p!(Path.dirname(out_path))

    args =
      [
        "ggen_igniter.sync",
        "--pack-dir",
        pack_dir,
        "--template",
        template_path
      ] ++
        if for_each do
          ["--for-each", for_each, "--out", out_path]
        else
          ["--out", out_path]
        end

    case System.cmd("mix", args, cd: @repo, stderr_to_stdout: true) do
      {out, 0} -> out
      {out, code} -> flunk("mix #{Enum.join(args, " ")} exited #{code}:\n#{out}")
    end
  end

  # `for_each` templates fan out one render per bound item; forcing them
  # through a single --out is refused by ggen_igniter as a
  # duplicate-output-path error, so each for_each recipe carries its own
  # EEx out pattern over the for_each bindings.
  defp render_all(name, pack_dir \\ nil) do
    dir = scratch(name)
    pack = pack_dir || Path.join(@repo, @pack)

    for {tpl, for_each, out_pattern} <- @render_recipes do
      tpl_path = Path.join(pack, "templates/" <> tpl)

      if for_each do
        sync(pack, tpl_path, Path.join(dir, out_pattern), for_each)
      else
        sync(pack, tpl_path, Path.join(dir, out_pattern))
      end
    end

    dir
  end

  defp snapshot(dir) do
    Path.wildcard(Path.join(dir, "**/*"))
    |> Enum.filter(&File.regular?/1)
    |> Map.new(&{Path.relative_to(&1, dir), File.read!(&1)})
  end

  defp ontology_graph(pack_dir) do
    RDF.Turtle.read_file!(Path.join(pack_dir, "ontology.ttl"))
  end

  defp gate_rows(graph, gate_rel, pack_dir \\ nil) do
    path =
      if pack_dir do
        Path.join(pack_dir, gate_rel)
      else
        Path.join([@repo, @pack, gate_rel])
      end

    length(GgenIgniter.Query.Oxigraph.run(graph, File.read!(path)))
  end

  # ---------------------------------------------------------------------------
  # Court 1: render all templates
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "render: all templates render non-empty with provenance header" do
    dir = render_all("render")
    rendered = snapshot(dir)

    assert map_size(rendered) == 38,
           "expected 38 rendered files (4 single + 11+11+4+4+4 fan-out), got #{map_size(rendered)}"

    # Every shipped .eex template is either rendered or typed-excluded.
    rendered_or_excluded = @render_recipes |> Enum.map(&elem(&1, 0)) |> MapSet.new()

    for tpl <- @templates do
      assert MapSet.member?(rendered_or_excluded, tpl) or tpl in @excluded_templates,
             "template #{tpl} is neither rendered nor typed-excluded"
    end

    for {out_rel, content} <- rendered do
      assert content != "" and String.trim(content) != "", "empty render: #{out_rel}"
      assert content =~ "GENERATED by ggen_igniter", "missing provenance header: #{out_rel}"
    end
  end

  # ---------------------------------------------------------------------------
  # Court 2: determinism
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "determinism: two independent full renders are byte-identical" do
    a = snapshot(render_all("render-a"))
    b = snapshot(render_all("render-b"))

    assert map_size(a) == 38
    assert map_size(a) == map_size(b)

    assert a == b, "two renders of the same pack diverged - generation is not deterministic"
  end

  # ---------------------------------------------------------------------------
  # Courts 3+4: witness gates (exact counts) + offender companions (0 = clean)
  # ---------------------------------------------------------------------------

  test "gates: 15 witness gates and 15 offender companions score per convention" do
    graph = ontology_graph(Path.join(@repo, @pack))

    for {gate, expected} <- @gates do
      rows = gate_rows(graph, gate)
      assert rows == expected, "gate #{gate}: expected #{expected} rows, got #{rows}"
    end

    for companion <- @offender_gates do
      rows = gate_rows(graph, companion)
      assert rows == 0, "offender companion #{companion}: expected 0 rows (clean), got #{rows}"
    end
  end

  # ---------------------------------------------------------------------------
  # Court 5: anti-vacuity mutation (tmp pack copy only)
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "anti-vacuity: corrupting one Capability in a tmp pack copy changes gate + render output" do
    baseline = snapshot(render_all("mutation-baseline"))

    corrupt = scratch("mutation-corrupt-pack")
    corrupt_pack = Path.join(corrupt, "pack")
    File.cp_r!(Path.join(@repo, @pack), corrupt_pack)

    ontology_path = Path.join(corrupt_pack, "ontology.ttl")
    ttl = File.read!(ontology_path)

    needle = ~s(ap:cap_Domain_Create a ap:Capability ; ap:capabilityId "Domain.Create" ;)
    assert ttl =~ needle, "corruption target triple not found in pack ontology"

    replacement =
      ~s(ap:cap_Domain_Create a ap:MutatedCapability ; ap:capabilityId "Domain.Create" ;)

    corrupted = String.replace(ttl, needle, replacement, count: 1)
    assert corrupted != ttl, "corruption changed nothing"
    File.write!(ontology_path, corrupted)

    # (a) GATE SENSITIVITY: 010_capabilities drops 31 -> 30 (the mutated
    # individual lost its ap:Capability class membership).
    graph = ontology_graph(corrupt_pack)

    assert gate_rows(graph, "gates/010_capabilities.rq", corrupt_pack) == 30,
           "gate 010_capabilities did not see the corruption (vacuous)"

    # (b) RENDER SENSITIVITY: re-render the capability catalog from the
    # corrupted pack copy; it must differ from the baseline.
    sync(
      corrupt_pack,
      Path.join(corrupt_pack, "templates/capability_catalog.ex.eex"),
      Path.join(corrupt, "capability_catalog.ex")
    )

    mutated_catalog = File.read!(Path.join(corrupt, "capability_catalog.ex"))

    refute mutated_catalog == Map.fetch!(baseline, "capability_catalog.ex"),
           "corrupted render still produced the pristine catalog (render is vacuous)"
  end
end
