defmodule AshPPlan.Courts.PackStoreConformanceCourtTest do
  @moduledoc """
  Pack court for `priv/ggen/ash-pplan-store-conformance-pack/`, following the
  `pack_chaos_court_test.exs` pattern (real ggen_igniter sync runs).

    1. RENDER — `store_conformance.ex.eex` renders via a real
       `mix ggen_igniter.sync` into a run-unique scratch under `tmp/`
       (one conformance suite; non-empty, provenance header, parseable).
    2. DETERMINISM — a second render is byte-identical.
    3. GATES — all 3 gates fire with exact row counts (20 / 14 / 36) via
       `GgenIgniter.Query.Oxigraph` against the shipped ontology.
    4. ANTI-VACUITY — a corrupt copy of the pack (one `sc:Callback` individual
       stripped of its class membership) drops gate 010 to 19 rows and the
       re-render no longer carries the callback's suite entry. A court that
       admits its own corruption is vacuous.

  Select-only court: no DO authority.
  """

  use ExUnit.Case, async: false

  @repo Path.expand("../..", __DIR__)
  @pack "priv/ggen/ash-pplan-store-conformance-pack"
  @template "templates/store_conformance.ex.eex"

  @gates [
    {"gates/010_callbacks.rq", 20},
    {"gates/020_laws.rq", 14},
    {"gates/030_covers.rq", 36}
  ]

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  defp scratch(name) do
    dir =
      Path.join(@repo, "tmp/court-5courts-store-#{name}-#{System.unique_integer([:positive])}")

    File.mkdir_p!(dir)

    ExUnit.Callbacks.on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  defp sync(pack_dir, out_path) do
    args = [
      "ggen_igniter.sync",
      "--pack-dir",
      pack_dir,
      "--template",
      Path.join(pack_dir, @template),
      "--out",
      out_path
    ]

    case System.cmd("mix", args, cd: @repo, stderr_to_stdout: true) do
      {out, 0} -> out
      {out, code} -> flunk("mix #{Enum.join(args, " ")} exited #{code}:\n#{out}")
    end
  end

  defp render_file(name, pack_dir \\ nil) do
    dir = scratch(name)
    pack = pack_dir || Path.join(@repo, @pack)
    out = Path.join(dir, "store_conformance.ex")
    sync(pack, out)
    {dir, out}
  end

  defp parse_check!(path) do
    case Code.string_to_quoted(File.read!(path)) do
      {:ok, ast} ->
        ast

      {:error, reason} ->
        flunk("rendered file does not parse as Elixir: #{path}\n#{inspect(reason)}")
    end
  end

  defp ontology_graph(pack_dir), do: RDF.Turtle.read_file!(Path.join(pack_dir, "ontology.ttl"))

  defp gate_rows(graph, gate_rel, pack_dir \\ nil) do
    path =
      if pack_dir, do: Path.join(pack_dir, gate_rel), else: Path.join([@repo, @pack, gate_rel])

    length(GgenIgniter.Query.Oxigraph.run(graph, File.read!(path)))
  end

  # ---------------------------------------------------------------------------
  # Court 1: render
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "render: conformance suite non-empty, provenance header, parseable" do
    {_dir, out} = render_file("render")
    content = File.read!(out)

    assert content != "" and String.trim(content) != "", "empty render"
    assert content =~ "GENERATED by ggen_igniter", "missing provenance header"
    parse_check!(out)
  end

  # ---------------------------------------------------------------------------
  # Court 2: determinism
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "determinism: two independent renders are byte-identical" do
    {_, a} = render_file("render-a")
    {_, b} = render_file("render-b")

    assert File.read!(a) == File.read!(b),
           "two renders of the same pack diverged — generation is not deterministic"
  end

  # ---------------------------------------------------------------------------
  # Court 3: gates (read-only, exact row counts)
  # ---------------------------------------------------------------------------

  test "gates: all 3 fire with exact row counts via oxigraph" do
    graph = ontology_graph(Path.join(@repo, @pack))

    for {gate, expected} <- @gates do
      rows = gate_rows(graph, gate)
      assert rows == expected, "gate #{gate}: expected #{expected} rows, got #{rows}"
    end
  end

  # ---------------------------------------------------------------------------
  # Court 4: anti-vacuity mutation (tmp pack copy only)
  # ---------------------------------------------------------------------------

  @tag timeout: 600_000
  test "anti-vacuity: corrupting one Callback in a tmp pack copy changes gate + render output" do
    {_, baseline} = render_file("mutation-baseline")

    corrupt = scratch("mutation-corrupt-pack")
    corrupt_pack = Path.join(corrupt, "pack")
    File.cp_r!(Path.join(@repo, @pack), corrupt_pack)

    ontology_path = Path.join(corrupt_pack, "ontology.ttl")
    ttl = File.read!(ontology_path)
    needle = "sc:cb_get_run a sc:Callback ;"

    assert ttl =~ needle, "corruption target triple not found in pack ontology"

    corrupted = String.replace(ttl, needle, "sc:cb_get_run a sc:NotACallback ;", count: 1)
    assert corrupted != ttl, "corruption changed nothing"
    File.write!(ontology_path, corrupted)

    # (a) GATE SENSITIVITY: 010_callbacks drops 20 -> 19 on the corrupted graph.
    graph = ontology_graph(corrupt_pack)

    assert gate_rows(graph, "gates/010_callbacks.rq", corrupt_pack) == 19,
           "gate 010_callbacks did not see the corruption (vacuous)"

    # (b) RENDER SENSITIVITY: re-render from the corrupted pack copy; the
    # get_run callback's arity tuple must leave the rendered callback table
    # (its name may still appear inside law bodies, which is fine).
    {_, mutated} = render_file("mutation-render", corrupt_pack)
    mutated_content = File.read!(mutated)

    refute mutated_content =~ ~s|{:get_run, 2}|,
           "corrupted render still carried the stripped callback tuple (render is vacuous)"

    assert File.read!(baseline) =~ ~s|{:get_run, 2}|,
           "baseline render unexpectedly lacks {:get_run, 2} — corruption needle mis-aimed"
  end
end
