# GENERATED by ggen_igniter from ontology.ttl (Spark DSL extension row ap:dslSection).
# Do not edit. Regenerate with priv/ggen/ash-pplan-dsl-pack/bin/manufacture-dsl.
defmodule AshPPlan.Dsl.PPlan do
  @moduledoc """
  GENERATED project-local Spark DSL section (openQuestion 4, v26.10.3): the
  project exposes its own DSL instead of composing existing DSLs verbosely.

      defmodule MyFlow do
        use AshPPlan.Dsl

        pplan do
          goal "ship"
          task :observe, capability: "Repository.Observe"
          task :build, capability: "Work.Select", after: [:observe]
        end
      end

  `pplan` entities are lifted into the `[:workflow]` section by
  `AshPPlan.Dsl.PPlan.Lift` at compile time, so every existing verifier and
  the generated `__ash_pplan_workflow__/0` apply unchanged. Semantics only;
  authority never exceeds `:construct`.
  """

  alias AshPPlan.Workflow.Dsl.{Method, Task}

  @task %Spark.Dsl.Entity{
    name: :task,
    describe: "A capability requirement with ordering, outcomes and properties.",
    target: Task,
    args: [:id],
    identifier: :id,
    schema: [
      id: [type: :atom, required: true, doc: "Unique task id."],
      capability: [type: {:or, [:string, :atom]}, required: true, doc: "`Family.Name`."],
      after: [type: {:list, :atom}, default: [], doc: "Task ids this task depends on."],
      outcomes: [type: {:list, :atom}, default: [], doc: "Declared nondeterministic outcomes."],
      properties: [type: {:list, :atom}, default: [], doc: "Execution properties."],
      evidence: [type: {:list, :atom}, default: [], doc: "Required evidence kinds."],
      authority: [type: :atom, default: :construct, doc: "Authority ceiling (max :construct)."]
    ]
  }

  @method %Spark.Dsl.Entity{
    name: :method,
    describe: "An HDDL decomposition of a compound task into ordered subtasks.",
    target: Method,
    args: [:id],
    identifier: :id,
    schema: [
      id: [type: :atom, required: true],
      task: [type: :atom, required: true, doc: "The compound task refined."],
      subtasks: [type: {:list, :atom}, default: [], doc: "Ordered declared task ids."],
      precondition: [type: :any, doc: "Optional applicability condition."]
    ]
  }

  @workflow %Spark.Dsl.Section{
    name: :pplan,
    describe: "Generated P-PLAN/PROV-O workflow section (lifts into [:workflow]).",
    schema: [
      name: [type: {:or, [:atom, :string]}, doc: "Workflow name (default: module name)."],
      goal: [type: {:or, [:string, :atom]}, doc: "Workflow goal."],
      version: [type: :pos_integer, default: 1]
    ],
    entities: [@method, @task]
  }

  use Spark.Dsl.Extension,
    sections: [@workflow],
    transformers: [
      Elixir.AshPPlan.Dsl.PPlan.Lift,
      Elixir.AshPPlan.Workflow.Dsl.Transformers.GenerateModel
    ],
    verifiers: [
      Elixir.AshPPlan.Workflow.Dsl.Verifiers.UniqueIds,
      Elixir.AshPPlan.Workflow.Dsl.Verifiers.CapabilitiesParse,
      Elixir.AshPPlan.Workflow.Dsl.Verifiers.AcyclicDependencies,
      Elixir.AshPPlan.Workflow.Dsl.Verifiers.OutcomeClosure
    ]
end
