# Court: the ontology-only authoring guarantee. The `ontology_only` workflow is
# authored exclusively as TTL rows in test/support/examples/ontology/examples.ttl
# (no consumer-authored Elixir). The runner is generated by bin/manufacture-examples
# from those rows. This court falsifies:
#   1. the runner file is a ggen artifact (GENERATED header), i.e. authored by
#      manufacture, not by hand;
#   2. the generated runner executes the workflow end-to-end through the
#      durable engine: run_durable parks on the `confirm` gate, signal+resume
#      completes the run;
#   3. an in-process `run/2` attempt on a durable-requiring workflow is refused
#      with a typed error (durable tasks need the ledger), keeping the durable
#      path the only lawful execution path;
#   4. the generated workflow module's subject matches the runner's (identity,
#      not drift).
defmodule AshPPlan.Courts.Examples.OntologyOnlyRunnerCourt do
  @moduledoc false
  use ExUnit.Case, async: false

  alias AshPPlan.Reactor.Durable.Clock
  alias AshPPlan.Reactor.Durable.Store.Ets
  alias AshPPlan.Workflow.Runtime

  @runner_path "test/support/examples/runners/ontology_only.ex"
  @runner AshPPlan.Examples.Runners.OntologyOnly
  @workflow AshPPlan.Examples.Workflows.OntologyOnly

  setup do
    Clock.use_test_clock()
    on_exit(&Clock.reset/0)
    :ok
  end

  test "runner is a generated artifact wired to the TTL-declared workflow" do
    assert File.exists?(@runner_path)
    header = @runner_path |> File.read!() |> String.split("\n") |> hd()
    assert header =~ "GENERATED by ggen_igniter"

    assert @runner.model() == @workflow.model()
    assert @runner.subject() == @workflow.subject()
  end

  test "generated runner completes a durable run with zero consumer Elixir" do
    assert {:ok, state} = @runner.run_durable()
    assert {:halted, %{run_id: run_id, store: store}} = state.outcome
    on_exit(fn -> stop_store(store) end)

    assert %{state: :halted} = state.observation
    assert {:ok, explained} = Runtime.explain(state)
    assert [wait] = explained.durable.waiting_on
    assert wait =~ "confirm"

    # Deliver the TTL-declared `confirm` gate signal and resume: the ledger
    # completes both tasks and stores the checkpoints.
    assert {:ok, resumed} = @runner.resume(state, signal: {wait, %{approved: true}})
    assert %{state: :succeeded} = resumed.observation
    assert {:ok, _result} = resumed.outcome

    ledger = store |> Ets.list_runs() |> Enum.find(&(&1.id == run_id))
    assert ledger.status == :completed

    labels =
      store
      |> AshPPlan.Reactor.Durable.Engine.steps(run_id)
      |> Enum.map(& &1.label)

    assert Enum.any?(labels, &(&1 =~ "confirm"))
    assert Enum.any?(labels, &(&1 =~ "wakeup"))
  end

  test "durable-requiring workflow cannot complete on the in-process path (typed sealing)" do
    assert {:ok, state} = @runner.run()
    assert %{state: :failed} = state.observation

    # The gate provider is sealed: the durable ledger is the only lawful path.
    assert state.registry.sealed[AshPPlan.Providers.DurableGate] == {:failed, :confirm}
  end

  defp stop_store(store) do
    if is_pid(store) or is_atom(store) do
      GenServer.stop(store, :normal)
    end
  catch
    :exit, _ -> :ok
  end
end
