# GENERATED by ggen_igniter from ash-extension-core-pack ontology.ttl (aex:AshPPlanAshReactorExtended).
# Do not edit. Regenerate with ./bin/manufacture.

defmodule AshPPlan.Reactor.Adapters.AshReactorExtended do
  @moduledoc """
  Companion adapter extending `AshPPlan.Reactor.Adapters.AshReactor`'s
  domain-action coverage (create/read/update/destroy/action) with the
  Ash.Reactor step kinds it does not implement itself: generic actions,
  ash_step, read_one, load, and the bulk kinds. Generated from
  `aex:AshPPlanAshReactorExtended` (`aex:ReactorAdapterSpec`) and its
  `aex:ReactorAdapterOp` rows in the ash-extension-core-pack ontology --
  regenerate, do not hand-edit.
  """
  @behaviour AshPPlan.Reactor.Adapter

  @impl true
  def id, do: :ash_reactor_extended

  @impl true
  def available?, do: Code.ensure_loaded?(Ash.Reactor)

  @impl true
  def ops,
    do: [
      :ash_generic,
      :ash_step,
      :ash_read_one,
      :ash_load,
      :bulk_create,
      :bulk_update,
      :bulk_destroy
    ]

  @table %{
    ash_generic: {Ash.Reactor.ActionStep, []},
    ash_step: {Ash.Reactor.AshStep, []},
    ash_read_one: {Ash.Reactor.ReadOneStep, []},
    ash_load: {Ash.Reactor.LoadStep, []},
    bulk_create: {Ash.Reactor.BulkCreateStep, []},
    bulk_update: {Ash.Reactor.BulkUpdateStep, []},
    bulk_destroy: {Ash.Reactor.BulkDestroyStep, []}
  }

  @impl true
  def step(op, options), do: AshPPlan.Reactor.Adapter.resolve(__MODULE__, @table, op, options)
end
