# GENERATED by ggen_igniter from ontology.ttl (workflow file_release).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Examples.Workflows.FileRelease do
  @moduledoc """
  Generated workflow `file_release` (goal `release_file`): the canonical model literal and its identity.
  """

  alias AshPPlan.Workflow.{Model, Subject}

  @spec model() :: Model.t()
  def model do
    {:ok, model} =
      Model.new(
        name: "file_release",
        goal: "release_file",
        tasks: [
          %{
            id: :fetch,
            capability: "Remote.Read",
            depends_on: [],
            outcomes: [:success],
            properties: [:retryable],
            authority: :observe
          },
          %{
            id: :write,
            capability: "File.Write",
            depends_on: [:fetch],
            outcomes: [:success],
            properties: [:compensable],
            authority: :construct
          },
          %{
            id: :verify,
            capability: "Verification.Run",
            depends_on: [:write],
            outcomes: [:admitted, :failed, :insufficient_evidence],
            properties: [:observable],
            authority: :observe
          }
        ],
        methods: []
      )

    model
  end

  @spec subject() :: map()
  def subject, do: Subject.bind(model())

  @spec hddl() :: String.t()
  def hddl, do: AshPPlan.Workflow.Project.HDDL.render(model())
end
