# GENERATED by ggen_igniter from ontology.ttl (workflow ontology_only).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Examples.Workflows.OntologyOnly do
  @moduledoc """
  Generated workflow `ontology_only` (goal `ontology_only_release`): the canonical model literal and its identity.
  """

  alias AshPPlan.Workflow.{Model, Subject}

  @spec model() :: Model.t()
  def model do
    {:ok, model} =
      Model.new(
        name: "ontology_only",
        goal: "ontology_only_release",
        tasks: [
          %{
            id: :confirm,
            capability: "Human.Approve",
            depends_on: [],
            outcomes: [:approved],
            properties: [:durable],
            authority: :select
          },
          %{
            id: :wakeup,
            capability: "Schedule.Deferred",
            depends_on: [:confirm],
            outcomes: [:success],
            properties: [:durable],
            authority: :observe
          }
        ],
        methods: []
      )

    model
  end

  @spec subject() :: map()
  def subject, do: Subject.bind(model())

  @spec hddl() :: String.t()
  def hddl, do: AshPPlan.Workflow.Project.HDDL.render(model())
end
