# GENERATED by ggen_igniter from ontology.ttl (workflow selfhost).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Examples.Workflows.Selfhost do
  @moduledoc """
  Generated workflow `selfhost` (goal `close_selfhost_frontier`): the canonical model literal and its identity.
  """

  alias AshPPlan.Workflow.{Model, Subject}

  @spec model() :: Model.t()
  def model do
    {:ok, model} =
      Model.new(
        name: "selfhost",
        goal: "close_selfhost_frontier",
        tasks: [
          %{
            id: :observe,
            capability: "Repository.Observe",
            depends_on: [],
            outcomes: [:success],
            properties: [:compensable, :observable],
            authority: :observe
          },
          %{
            id: :select,
            capability: "Work.Select",
            depends_on: [:observe],
            outcomes: [:success],
            properties: [:observable],
            authority: :select
          },
          %{
            id: :execute,
            capability: "Agent.Execute",
            depends_on: [:select],
            outcomes: [:refused, :success],
            properties: [:durable, :resumable],
            authority: :construct
          },
          %{
            id: :integration_gate,
            capability: "Human.Approve",
            depends_on: [:execute],
            outcomes: [:approved],
            properties: [:checkpointed, :durable, :resumable],
            authority: :select
          },
          %{
            id: :integrate,
            capability: "Repository.Integrate",
            depends_on: [:integration_gate],
            outcomes: [:merged],
            properties: [:compensable, :observable],
            authority: :construct
          },
          %{
            id: :verify,
            capability: "Verification.Run",
            depends_on: [:integrate],
            outcomes: [:admitted, :failed],
            properties: [:observable],
            authority: :observe
          },
          %{
            id: :record_standing,
            capability: "Evidence.Record",
            depends_on: [:verify],
            outcomes: [:success],
            properties: [:durable],
            authority: :observe
          }
        ],
        methods: [
          %{
            id: :close_selfhost_frontier_loop,
            task: :close_selfhost_frontier,
            subtasks: [
              :observe,
              :select,
              :execute,
              :integration_gate,
              :integrate,
              :verify,
              :record_standing
            ]
          }
        ]
      )

    model
  end

  @spec subject() :: map()
  def subject, do: Subject.bind(model())

  @spec hddl() :: String.t()
  def hddl, do: AshPPlan.Workflow.Project.HDDL.render(model())
end
