# GENERATED by ggen_igniter from ontology.ttl (workflow ultracode).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Examples.Workflows.Ultracode do
  @moduledoc """
  Generated workflow `ultracode` (goal `close_frontier`): the canonical model literal and its identity.
  """

  alias AshPPlan.Workflow.{Model, Subject}

  @spec model() :: Model.t()
  def model do
    {:ok, model} =
      Model.new(
        name: "ultracode",
        goal: "close_frontier",
        tasks: [
          %{
            id: :observe,
            capability: "Repository.Observe",
            depends_on: [],
            outcomes: [:success],
            properties: [],
            authority: :observe
          },
          %{
            id: :select,
            capability: "Work.Select",
            depends_on: [:observe],
            outcomes: [:success],
            properties: [],
            authority: :select
          },
          %{
            id: :execute,
            capability: "Agent.Execute",
            depends_on: [:select],
            outcomes: [:failed, :refused, :success, :unavailable],
            properties: [:durable],
            authority: :construct
          },
          %{
            id: :integrate,
            capability: "Repository.Integrate",
            depends_on: [:execute],
            outcomes: [:conflict, :merged, :stale],
            properties: [],
            authority: :construct
          },
          %{
            id: :verify,
            capability: "Verification.Run",
            depends_on: [:integrate],
            outcomes: [:admitted, :failed, :insufficient_evidence],
            properties: [],
            authority: :observe
          }
        ],
        methods: [
          %{
            id: :close_frontier_default,
            task: :close_frontier,
            subtasks: [:observe, :select, :execute, :integrate, :verify]
          },
          %{
            id: :close_frontier_degraded,
            task: :close_frontier,
            subtasks: [:observe, :select, :verify]
          }
        ]
      )

    model
  end

  @spec subject() :: map()
  def subject, do: Subject.bind(model())

  @spec hddl() :: String.t()
  def hddl, do: AshPPlan.Workflow.Project.HDDL.render(model())
end
