defmodule AshPPlan.Reactor.GenericActionBridge.Domain do
  @moduledoc false
  use Ash.Domain, validate_config_inclusion?: false

  resources do
    resource(AshPPlan.Reactor.GenericActionBridge)
  end
end

defmodule AshPPlan.Reactor.GenericActionBridge do
  @moduledoc """
  GENERATED by ggen_igniter from the ash-extension-core-pack ontology
  (aex:ReactorActionBridge). Do not edit; regenerate with
  `mix ggen_igniter.sync --pack-dir <ash-extension-core-pack> --template
  templates/generic_action_bridge.ex.tmpl --engine oxigraph
  --out lib/ash_pplan/reactor/generic_action_bridge.ex`.

  Binds a Reactor module (AshPPlan.Reactor.GenericActionBridge.Workflow) directly as the `run` of an
  Ash generic action (run_reactor) -- the documented preferred
  initiation pattern for Reactor-backed generic actions.

  Caveats (admitted facts, carried as doc comments):
  * Every Reactor input must map to an action argument. This bridge enforces
    the mapping at runtime: check_input_mapping/0 compares the inputs
    admitted in the ontology against the compiled action arguments and
    refuses on any unmapped input.
  * `transaction? true` on the action forces the Reactor to run
    synchronously (async?: false), so every step executes inside the
    enclosing transaction. This bridge declares transactional: false.
  """

  use Ash.Resource,
    domain: AshPPlan.Reactor.GenericActionBridge.Domain,
    data_layer: Ash.DataLayer.Ets

  ets do
    private?(true)
  end

  attributes do
    uuid_primary_key(:id)
  end

  actions do
    defaults([:read])

    action :run_reactor, :map do
      argument(:value, :integer, allow_nil?: false)

      run(AshPPlan.Reactor.GenericActionBridge.Workflow)
    end
  end

  @doc """
  Runtime check that every admitted Reactor input maps to a real action
  argument on run_reactor. Returns `{:error, {:unmapped_inputs, ...}}`
  when the bound reactor has an input the action does not accept.
  """
  def check_input_mapping do
    arguments =
      AshPPlan.Reactor.GenericActionBridge
      |> Ash.Resource.Info.action(:run_reactor)
      |> Map.fetch!(:arguments)
      |> MapSet.new(& &1.name)

    admitted = MapSet.new(input_names())

    case MapSet.difference(admitted, arguments) |> MapSet.to_list() do
      [] -> :ok
      unmapped -> {:error, {:unmapped_inputs, unmapped}}
    end
  end

  @doc "Reactor inputs admitted in the ontology for the bound reactor."
  def input_names do
    [:value]
  end

  @doc "Atom names of the action arguments rendered from the same input rows."
  def argument_names do
    [:value]
  end
end

defmodule AshPPlan.Reactor.GenericActionBridge.Workflow do
  @moduledoc """
  GENERATED Reactor bound as the `run` of `AshPPlan.Reactor.GenericActionBridge.run_reactor/2`.
  One `input` per action argument (checked by check_input_mapping/0).
  """
  use Reactor

  input(:value)

  step :bridge_step do
    argument(:value, input(:value))

    run(fn arguments, _context ->
      {:ok, %{bridged: arguments}}
    end)
  end

  return(:bridge_step)
end
