# GENERATED by ggen_igniter from ontology.ttl (provider domain).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Providers.Domain do
  @moduledoc """
  Generated provider `domain`: describes how capabilities are realized (adapter + operation bindings).
  It names no Reactor implementation; `AshPPlan.Reactor` binds realizations to steps.

  Qualification refuses any authority above `:construct`; availability is not authority.
  """
  @behaviour AshPPlan.Provider

  alias AshPPlan.Providers.Qualify

  @capabilities [
    "Domain.Action",
    "Domain.Create",
    "Domain.Destroy",
    "Domain.Read",
    "Domain.Update"
  ]
  @properties [:policy_checked, :transactional]
  @evidence [:ash_result]
  @authorities [:none, :observe, :select, :plan, :construct]
  @table %{
    "Domain.Action" => {:ash_reactor, :domain_action, [kind: :action]},
    "Domain.Create" => {:ash_reactor, :domain_create, [kind: :create]},
    "Domain.Destroy" => {:ash_reactor, :domain_destroy, [kind: :destroy]},
    "Domain.Read" => {:ash_reactor, :domain_read, [kind: :read]},
    "Domain.Update" => {:ash_reactor, :domain_update, [kind: :update]}
  }

  @impl true
  def id, do: :domain
  @impl true
  def capabilities, do: @capabilities
  @impl true
  def properties, do: @properties
  @impl true
  def evidence, do: @evidence
  @impl true
  def cost, do: 1

  @impl true
  def qualify(requirement, context) do
    with :ok <-
           Qualify.check(
             requirement,
             context,
             @capabilities,
             @properties,
             @evidence,
             @authorities
           ) do
      :ok
    end
  end

  @impl true
  def realize(requirement, context) do
    with :ok <- qualify(requirement, context) do
      Qualify.realize(requirement, id(), @table, @properties)
    end
  end
end
