# GENERATED by ggen_igniter from ontology.ttl (provider event_state).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Providers.EventState do
  @moduledoc """
  Generated provider `event_state`: describes how capabilities are realized (adapter + operation bindings).
  It names no Reactor implementation; `AshPPlan.Reactor` binds realizations to steps.

  Qualification refuses any authority above `:construct`; availability is not authority.
  """
  @behaviour AshPPlan.Provider

  alias AshPPlan.Providers.Qualify

  @capabilities [
    "Actuation.Actuate",
    "Actuation.Command",
    "Event.Await",
    "State.Await",
    "State.Observe"
  ]
  @properties [:pollable]
  @evidence [:observation]
  @authorities [:none, :observe, :select, :plan, :construct]
  @table %{
    "Actuation.Actuate" => {:local, :actuation_actuate, []},
    "Actuation.Command" => {:local, :actuation_command, []},
    "Event.Await" => {:durable, :event_await, []},
    "State.Await" => {:durable, :state_await, []},
    "State.Observe" => {:local, :state_observe, [mode: :observe]}
  }

  @impl true
  def id, do: :event_state
  @impl true
  def capabilities, do: @capabilities
  @impl true
  def properties, do: @properties
  @impl true
  def evidence, do: @evidence
  @impl true
  def cost, do: 2

  @impl true
  def qualify(requirement, context) do
    with :ok <-
           Qualify.check(
             requirement,
             context,
             @capabilities,
             @properties,
             @evidence,
             @authorities
           ) do
      :ok
    end
  end

  @impl true
  def realize(requirement, context) do
    with :ok <- qualify(requirement, context) do
      Qualify.realize(requirement, id(), @table, @properties)
    end
  end
end
