# GENERATED by ggen_igniter from ontology.ttl (provider file).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Providers.File do
  @moduledoc """
  Generated provider `file`: describes how capabilities are realized (adapter + operation bindings).
  It names no Reactor implementation; `AshPPlan.Reactor` binds realizations to steps.

  Qualification refuses any authority above `:construct`; availability is not authority.
  """
  @behaviour AshPPlan.Provider

  alias AshPPlan.Providers.Qualify

  @capabilities ["File.Copy", "File.Delete", "File.Mkdir", "File.Read", "File.Write"]
  @properties [:compensable]
  @evidence [:file_stat]
  @authorities [:none, :observe, :select, :plan, :construct]
  @table %{
    "File.Copy" => {:reactor_file, :file_copy, [revert_on_undo?: true]},
    "File.Delete" => {:reactor_file, :file_delete, [revert_on_undo?: true]},
    "File.Mkdir" => {:reactor_file, :file_mkdir, [revert_on_undo?: true]},
    "File.Read" => {:reactor_file, :file_read, []},
    "File.Write" => {:reactor_file, :file_write, [revert_on_undo?: true]}
  }

  @impl true
  def id, do: :file
  @impl true
  def capabilities, do: @capabilities
  @impl true
  def properties, do: @properties
  @impl true
  def evidence, do: @evidence
  @impl true
  def cost, do: 1

  @impl true
  def qualify(requirement, context) do
    with :ok <-
           Qualify.check(
             requirement,
             context,
             @capabilities,
             @properties,
             @evidence,
             @authorities
           ) do
      :ok
    end
  end

  @impl true
  def realize(requirement, context) do
    with :ok <- qualify(requirement, context) do
      Qualify.realize(requirement, id(), @table, @properties)
    end
  end
end
