# GENERATED by ggen_igniter from ontology.ttl.
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Providers.Index do
  @moduledoc false

  @modules [
    AshPPlan.Providers.Domain,
    AshPPlan.Providers.File,
    AshPPlan.Providers.Observation,
    AshPPlan.Providers.Process,
    AshPPlan.Providers.Durability,
    AshPPlan.Providers.DurableDispatch,
    AshPPlan.Providers.EventState,
    AshPPlan.Providers.Scheduling,
    AshPPlan.Providers.Network,
    AshPPlan.Providers.Remote,
    AshPPlan.Providers.A2a
  ]

  @spec modules() :: [module()]
  def modules, do: @modules
end
