# GENERATED by ggen_igniter from ontology.ttl (provider process).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Providers.Process do
  @moduledoc """
  Generated provider `process`: describes how capabilities are realized (adapter + operation bindings).
  It names no Reactor implementation; `AshPPlan.Reactor` binds realizations to steps.

  Qualification refuses any authority above `:construct`; availability is not authority.
  """
  @behaviour AshPPlan.Provider

  alias AshPPlan.Providers.Qualify

  @capabilities ["Process.Count", "Process.Start", "Process.Terminate"]
  @properties [:compensable]
  @evidence [:process_result]
  @authorities [:none, :observe, :select, :plan, :construct]
  @table %{
    "Process.Count" => {:reactor_process, :process_count, []},
    "Process.Start" => {:reactor_process, :process_start, []},
    "Process.Terminate" => {:reactor_process, :process_terminate, []}
  }

  @impl true
  def id, do: :process
  @impl true
  def capabilities, do: @capabilities
  @impl true
  def properties, do: @properties
  @impl true
  def evidence, do: @evidence
  @impl true
  def cost, do: 1

  @impl true
  def qualify(requirement, context) do
    with :ok <-
           Qualify.check(
             requirement,
             context,
             @capabilities,
             @properties,
             @evidence,
             @authorities
           ) do
      Qualify.adapter_available(AshPPlan.Reactor.Adapters.ReactorProcess)
    end
  end

  @impl true
  def realize(requirement, context) do
    with :ok <- qualify(requirement, context) do
      Qualify.realize(requirement, id(), @table, @properties)
    end
  end
end
