# GENERATED by ggen_igniter from ontology.ttl (provider remote).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Providers.Remote do
  @moduledoc """
  Generated provider `remote`: describes how capabilities are realized (adapter + operation bindings).
  It names no Reactor implementation; `AshPPlan.Reactor` binds realizations to steps.

  Qualification refuses any authority above `:construct`; availability is not authority.
  """
  @behaviour AshPPlan.Provider

  alias AshPPlan.Providers.Qualify

  @capabilities ["Remote.Read"]
  @properties [:retryable]
  @evidence [:http_response]
  @authorities [:none, :observe, :select, :plan, :construct]
  @table %{
    "Remote.Read" => {:reactor_req, :remote_read, [fun: :get]}
  }

  @impl true
  def id, do: :remote
  @impl true
  def capabilities, do: @capabilities
  @impl true
  def properties, do: @properties
  @impl true
  def evidence, do: @evidence
  @impl true
  def cost, do: 3

  @impl true
  def qualify(requirement, context) do
    with :ok <-
           Qualify.check(
             requirement,
             context,
             @capabilities,
             @properties,
             @evidence,
             @authorities
           ) do
      :ok
    end
  end

  @impl true
  def realize(requirement, context) do
    with :ok <- qualify(requirement, context) do
      Qualify.realize(requirement, id(), @table, @properties)
    end
  end
end
