PREFIX ap: <https://w3id.org/ash-pplan#>
SELECT DISTINCT ?workflow ?task ?outcome WHERE {
  ?w a ap:Workflow ; ap:workflowName ?workflow ; ap:hasTask ?t .
  ?t ap:taskId ?task ; ap:outcome ?outcome .
}
ORDER BY ?workflow ?task ?outcome
