PREFIX ap: <https://w3id.org/ash-pplan#>
SELECT DISTINCT ?provider_id ?property WHERE {
  ?p a ap:Provider ; ap:providerId ?provider_id ; ap:supportsProperty ?property .
  FILTER(STRSTARTS(STR(?p), "https://w3id.org/ash-pplan/examples#"))
}
ORDER BY ?provider_id ?property
