PREFIX ap: <https://w3id.org/ash-pplan#>
SELECT DISTINCT ?name ?goal WHERE {
  ?w a ap:Workflow ; ap:workflowName ?name ; ap:goal ?goal .
  FILTER(STRSTARTS(STR(?w), "https://w3id.org/ash-pplan/examples#"))
}
ORDER BY ?name
