# GENERATED by ggen_igniter from the examples ontology (runner for workflow file_release).
# Do not edit. Regenerate with bin/manufacture-examples.
#
# Ontology-only execution entry: declares no behavior of its own. It wires the
# generated workflow module, the generated provider index, the durable ETS
# store and the built-in adapter table into `AshPPlan.Workflow.Runtime`, so a
# user who only edits RDF never writes Elixir to run a declared workflow.
defmodule AshPPlan.Examples.Runners.FileRelease do
  @moduledoc """
  Generated ontology-only runner for workflow `file_release` (goal `release_file`).

  `run/2` executes in-process (DB-free). `run_durable/2` runs through the
  durable engine over a generated-registry selection, parking and resuming
  through the ledger. Both default the provider set to the generated index
  (`AshPPlan.Test.Examples.ProviderIndex`), so resolution, projection and
  execution need zero consumer-authored Elixir.
  """

  alias AshPPlan.Reactor.Durable.Store.Ets
  alias AshPPlan.Workflow.Runtime

  @workflow AshPPlan.Examples.Workflows.FileRelease
  @provider_index AshPPlan.Test.Examples.ProviderIndex

  @spec model() :: AshPPlan.Workflow.Model.t()
  def model, do: @workflow.model()

  @spec subject() :: map()
  def subject, do: @workflow.subject()

  @spec hddl() :: String.t()
  def hddl, do: @workflow.hddl()

  @doc """
  One in-process Reactor run of the declared workflow. Same contract as
  `AshPPlan.Workflow.Runtime.run/3`; the only default applied is the provider
  set (the generated index).
  """
  @spec run(map(), keyword()) :: {:ok, map()} | {:error, map()}
  def run(inputs \\ %{}, opts \\ []), do: Runtime.run(@workflow, inputs, default_opts(opts))

  @doc """
  Start and attempt a durable run of the declared workflow over an ETS ledger.
  Options: `:store` (default: a fresh `Ets` store linked to the caller),
  `:run_id` (default `file_release-run-<unique>`), plus every `Runtime.run/3`
  option. Returns the run state; on halt, use `signal/4` + `resume/2`.
  """
  @spec run_durable(map(), keyword()) :: {:ok, map()} | {:error, map()}
  def run_durable(inputs \\ %{}, opts \\ []) do
    {existing, opts} =
      Keyword.get_and_update(opts, :store, fn
        nil -> :pop
        store -> {store, store}
      end)

    store =
      case existing do
        nil ->
          case Ets.start_link() do
            {:ok, store} -> store
            {:error, {:already_started, store}} -> store
          end

        store ->
          store
      end

    run_id =
      Keyword.get_lazy(opts, :run_id, fn ->
        "file_release-run-#{System.unique_integer([:positive])}"
      end)

    Runtime.run(@workflow, inputs, [store: store, run_id: run_id] ++ default_opts(opts))
  end

  @doc "Deliver a signal to a durable run started by this runner."
  @spec signal(map(), String.t(), term(), keyword()) :: {:ok, term()} | {:error, map()}
  def signal(state, name, payload, opts \\ []),
    do: Runtime.signal(state, name, payload, opts)

  @doc "Resume a halted (or fail over a failed) durable run started by this runner."
  @spec resume(map(), keyword()) :: {:ok, map()} | {:error, map()}
  def resume(state, opts \\ []), do: Runtime.resume(state, default_opts(opts))

  defp default_opts(opts),
    do: Keyword.put_new_lazy(opts, :providers, fn -> @provider_index.modules() end)
end
