# GENERATED by ggen_igniter from ontology.ttl (provider selfhost_gate).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Providers.SelfhostGate do
  @moduledoc """
  Generated provider `selfhost_gate`: describes how capabilities are realized (adapter + operation bindings).
  It names no Reactor implementation; `AshPPlan.Reactor` binds realizations to steps.

  Qualification refuses any authority above `:construct`; availability is not authority.
  """
  @behaviour AshPPlan.Provider

  alias AshPPlan.Providers.Qualify

  @capabilities ["Human.Approve"]
  @properties [:checkpointed, :durable, :resumable]
  @evidence [:continuation]
  @authorities [:none, :observe, :select, :plan, :construct]
  @table %{
    "Human.Approve" =>
      {:durable, :human_approve, [signal: "selfhost_integration_gate", timeout: nil]}
  }

  @impl true
  def id, do: :selfhost_gate
  @impl true
  def capabilities, do: @capabilities
  @impl true
  def properties, do: @properties
  @impl true
  def evidence, do: @evidence
  @impl true
  def cost, do: 1

  @impl true
  def qualify(requirement, context) do
    with :ok <-
           Qualify.check(
             requirement,
             context,
             @capabilities,
             @properties,
             @evidence,
             @authorities
           ) do
      :ok
    end
  end

  @impl true
  def realize(requirement, context) do
    with :ok <- qualify(requirement, context) do
      Qualify.realize(requirement, id(), @table, @properties)
    end
  end
end
