# GENERATED by ggen_igniter from ontology.ttl (provider ultracode_verification).
# Do not edit. Regenerate with priv/ggen/ash-pplan-workflow-pack/bin/manufacture-workflow.
defmodule AshPPlan.Providers.UltracodeVerification do
  @moduledoc """
  Generated provider `ultracode_verification`: describes how capabilities are realized (adapter + operation bindings).
  It names no Reactor implementation; `AshPPlan.Reactor` binds realizations to steps.

  Qualification refuses any authority above `:construct`; availability is not authority.
  """
  @behaviour AshPPlan.Provider

  alias AshPPlan.Providers.Qualify

  @capabilities ["Verification.Run"]
  @properties [:observable]
  @evidence [:prov, :verdict]
  @authorities [:none, :observe, :select, :plan, :construct]
  @table %{
    "Verification.Run" => {:ultracode, :verification_run, []}
  }

  @impl true
  def id, do: :ultracode_verification
  @impl true
  def capabilities, do: @capabilities
  @impl true
  def properties, do: @properties
  @impl true
  def evidence, do: @evidence
  @impl true
  def cost, do: 1

  @impl true
  def qualify(requirement, context) do
    with :ok <-
           Qualify.check(
             requirement,
             context,
             @capabilities,
             @properties,
             @evidence,
             @authorities
           ) do
      :ok
    end
  end

  @impl true
  def realize(requirement, context) do
    with :ok <- qualify(requirement, context) do
      Qualify.realize(requirement, id(), @table, @properties)
    end
  end
end
