---------------------------- MODULE DurableProtocol ----------------------------
\* GENERATED by ggen_igniter from priv/ggen/ash-pplan-durable-tla-pack/ontology.ttl.
\* Do not edit. Regenerate with ./bin/manufacture-durable-tla.
\* One run, a set of workers, step "a" (effect) and step "b" (awaits a signal).
EXTENDS Integers, FiniteSets
CONSTANT Workers

Steps == {"a", "b"}
Statuses == {"cancelled", "cancelling", "completed", "failed", "pending", "polling", "unwind_blocked", "unwinding", "waiting"}
Terminal == {"cancelled", "completed", "failed"}
Parked == {"waiting", "polling"}
Forward == {"pending", "waiting", "polling"}

VARIABLES status, holder, pc, sigPending, sigDelivered, recorded, effects
vars == <<status, holder, pc, sigPending, sigDelivered, recorded, effects>>

Init ==
  /\ status = "pending"
  /\ holder = "none"
  /\ pc = [w \in Workers |-> "idle"]
  /\ sigPending = FALSE
  /\ sigDelivered = FALSE
  /\ recorded = [s \in Steps |-> FALSE]
  /\ effects = [s \in Steps |-> 0]

Cancel ==
  /\ status \in Forward \* guard:cancel_from
  /\ status' = "cancelling" /\ UNCHANGED <<holder, pc, sigPending, sigDelivered, recorded, effects>>

Claim(w) ==
  /\ status \notin Terminal \* guard:claim_nonterminal
  /\ holder = "none" \* guard:claim_free
  /\ pc[w] = "idle" \* guard:claim_idle
  /\ holder' = w /\ pc' = [pc EXCEPT ![w] = "running"] /\ UNCHANGED <<status, sigPending, sigDelivered, recorded, effects>>

Complete(w) ==
  /\ pc[w] = "running" \* guard:run_held
  /\ status \in Forward \* guard:settle_from
  /\ recorded["a"] = TRUE /\ recorded["b"] = TRUE \* guard:all_recorded
  /\ status' = "completed" /\ holder' = "none" /\ pc' = [pc EXCEPT ![w] = "idle"] /\ UNCHANGED <<sigPending, sigDelivered, recorded, effects>>

Deliver ==
  /\ sigDelivered = FALSE \* guard:deliver_once
  /\ sigPending' = TRUE /\ sigDelivered' = TRUE /\ UNCHANGED <<status, holder, pc, recorded, effects>>

Park(w) ==
  /\ pc[w] = "running" \* guard:run_held
  /\ status \in Forward \* guard:settle_from
  /\ recorded["a"] = TRUE /\ recorded["b"] = FALSE \* guard:parks_on_await
  /\ status' = "waiting" /\ holder' = "none" /\ pc' = [pc EXCEPT ![w] = "idle"] /\ UNCHANGED <<sigPending, sigDelivered, recorded, effects>>

RecordA(w) ==
  /\ pc[w] = "running" \* guard:run_held
  /\ status \in Forward \* guard:run_forward
  /\ recorded["a"] = FALSE \* guard:record_once
  /\ recorded' = [recorded EXCEPT !["a"] = TRUE] /\ effects' = [effects EXCEPT !["a"] = @ + 1] /\ UNCHANGED <<status, holder, pc, sigPending, sigDelivered>>

RecordB(w) ==
  /\ pc[w] = "running" \* guard:run_held
  /\ status \in Forward \* guard:run_forward
  /\ recorded["a"] = TRUE \* guard:await_after_a
  /\ sigPending \* guard:signal_available
  /\ recorded["b"] = FALSE \* guard:record_once
  /\ sigPending' = FALSE /\ recorded' = [recorded EXCEPT !["b"] = TRUE] /\ effects' = [effects EXCEPT !["b"] = @ + 1] /\ UNCHANGED <<status, holder, pc, sigDelivered>>

Release(w) ==
  /\ pc[w] = "running" \* guard:run_held
  /\ status \in Terminal \* guard:ended_terminal
  /\ holder' = "none" /\ pc' = [pc EXCEPT ![w] = "idle"] /\ UNCHANGED <<status, sigPending, sigDelivered, recorded, effects>>

Rollback(w) ==
  /\ pc[w] = "running" \* guard:run_held
  /\ status = "cancelling" \* guard:rollback_from
  /\ status' = "cancelled" /\ holder' = "none" /\ pc' = [pc EXCEPT ![w] = "idle"] /\ UNCHANGED <<sigPending, sigDelivered, recorded, effects>>

Quiescent ==
  /\ status \in Terminal
  /\ \A w \in Workers : pc[w] = "idle"
  /\ UNCHANGED vars

Next ==
  \/ Cancel
  \/ \E w \in Workers : Claim(w)
  \/ \E w \in Workers : Complete(w)
  \/ Deliver
  \/ \E w \in Workers : Park(w)
  \/ \E w \in Workers : RecordA(w)
  \/ \E w \in Workers : RecordB(w)
  \/ \E w \in Workers : Release(w)
  \/ \E w \in Workers : Rollback(w)
  \/ Quiescent

TypeOK == status \in Statuses /\ holder \in Workers \cup {"none"} /\ pc \in [Workers -> {"idle", "running"}] /\ sigPending \in BOOLEAN /\ sigDelivered \in BOOLEAN /\ recorded \in [Steps -> BOOLEAN] /\ \A s \in Steps : effects[s] \in Nat
ClaimExclusive == (\A w1, w2 \in Workers : (pc[w1] = "running" /\ pc[w2] = "running") => w1 = w2) /\ (\A w \in Workers : pc[w] = "running" <=> holder = w)
NoDoubleEffect == \A s \in Steps : effects[s] <= 1
TerminalAbsorbing == []([(status \in Terminal) => (status' = status)]_vars)
CancelNeverOverwritten == []([(status = "cancelling") => (status' \in {"cancelling", "cancelled", "unwind_blocked"})]_vars)
NoLostWakeup == (sigPending /\ status \in Parked) ~> ((\E w \in Workers : pc[w] = "running") \/ status \in Terminal)

Spec == Init /\ [][Next]_vars /\ \A w \in Workers : WF_vars(Claim(w))
=============================================================================
