# GENERATED by ggen_igniter from ontology.ttl (Spark DSL extension row ap:dslSection).
# Do not edit. Regenerate with priv/ggen/ash-pplan-dsl-pack/bin/manufacture-dsl.
defmodule AshPPlan.Dsl do
  @moduledoc """
  GENERATED `use`-able wrapper exposing the generated `pplan` section.

      defmodule MyFlow do
        use AshPPlan.Dsl

        pplan do
          goal "ship"
          task :observe, capability: "Repository.Observe"
        end
      end

  Resolving to a model: `AshPPlan.Workflow.model(MyFlow)` (the generated
  extension registers `AshPPlan.Workflow.Dsl.Transformers.GenerateModel`, so
  the module gains `__ash_pplan_workflow__/0`).
  """
  use Spark.Dsl,
    default_extensions: [extensions: [AshPPlan.Dsl.PPlan]]

  defdelegate model(module_or_model), to: AshPPlan.Workflow
end
