defmodule AshPPlan.ExecutionReceipt do
  @moduledoc """
  PROV-style observation of one semantic plan execution.

  This is evidence about an observed Reactor outcome. It is not a durable
  continuation checkpoint and grants no actuation authority.

  ## What the digest addresses

  The digest identifies the *observed outcome*, not the plan and not the run.
  Two runs of the same plan that observe the same result share a digest; that
  is the property that makes it a content address.

  A succeeded outcome is digested over the result term itself. A failed outcome
  is digested over the failure's identity — its exception module and message —
  rather than over the whole error struct, because a Reactor error carries
  references and pids that differ between two occurrences of the same failure.
  A halted outcome is digested over the halt state together with the steps that
  had completed and the results they produced, which is what a halt actually
  observes.

  The succeeded digest uses `:erlang.term_to_binary/2` in deterministic mode, so
  it is stable for a given Erlang/OTP release. It is evidence within a build,
  not a cross-version content address.
  """

  @enforce_keys [
    :plan_iri,
    :run_id,
    :status,
    :started_at,
    :finished_at,
    :duration_us,
    :outcome_digest
  ]
  defstruct [
    :plan_iri,
    :run_id,
    :status,
    :started_at,
    :finished_at,
    :duration_us,
    :outcome_digest
  ]

  @type status :: :succeeded | :halted | :failed | :unknown
  @type t :: %__MODULE__{
          plan_iri: String.t(),
          run_id: any(),
          status: status(),
          started_at: DateTime.t(),
          finished_at: DateTime.t(),
          duration_us: non_neg_integer(),
          outcome_digest: String.t()
        }

  @ap "https://w3id.org/ash-pplan#"
  @prov "http://www.w3.org/ns/prov#"
  @rdf_type "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
  @xsd_date_time "http://www.w3.org/2001/XMLSchema#dateTime"

  @doc """
  Renders a receipt as PROV-O N-Triples.

  The canonical ontology declares `ap:runIdentifier`, `ap:executionStatus` and
  `ap:resultDigest` on `ap:ExecutionReceipt`. This is where those terms are
  projected, so "PROV-style" names an executable serialization rather than a
  resemblance.

  The receipt is a `prov:Entity` generated by an `ap:SemanticExecution`
  activity, which in turn `prov:used` the plan it executed.
  """
  @spec to_rdf(t()) :: String.t()
  def to_rdf(%__MODULE__{} = receipt) do
    receipt_iri = "urn:ash-pplan:receipt:" <> receipt.outcome_digest

    execution_iri =
      "urn:ash-pplan:execution:" <>
        URI.encode(run_identifier(receipt.run_id), &URI.char_unreserved?/1)

    [
      {receipt_iri, @rdf_type, {:iri, @ap <> "ExecutionReceipt"}},
      {receipt_iri, @rdf_type, {:iri, @prov <> "Entity"}},
      {receipt_iri, @prov <> "wasGeneratedBy", {:iri, execution_iri}},
      {receipt_iri, @ap <> "runIdentifier", {:literal, run_identifier(receipt.run_id)}},
      {receipt_iri, @ap <> "executionStatus", {:literal, Atom.to_string(receipt.status)}},
      {receipt_iri, @ap <> "resultDigest", {:literal, receipt.outcome_digest}},
      {execution_iri, @rdf_type, {:iri, @ap <> "SemanticExecution"}},
      {execution_iri, @rdf_type, {:iri, @prov <> "Activity"}},
      {execution_iri, @prov <> "used", {:iri, receipt.plan_iri}},
      {execution_iri, @prov <> "startedAtTime",
       {:typed, DateTime.to_iso8601(receipt.started_at), @xsd_date_time}},
      {execution_iri, @prov <> "endedAtTime",
       {:typed, DateTime.to_iso8601(receipt.finished_at), @xsd_date_time}}
    ]
    |> Enum.map_join("", &triple/1)
  end

  @doc """
  Returns the run identity as a string.

  A run identity may be any term Reactor accepts, so it is normalised once here
  rather than at each projection boundary. A binary that is not valid UTF-8 is
  rendered with `inspect/1` so the result is always a valid string.
  """
  @spec run_identifier(any()) :: String.t()
  def run_identifier(run_id) when is_binary(run_id) do
    if String.valid?(run_id), do: run_id, else: inspect(run_id)
  end

  def run_identifier(run_id) when is_atom(run_id), do: Atom.to_string(run_id)
  def run_identifier(run_id) when is_integer(run_id), do: Integer.to_string(run_id)
  def run_identifier(run_id), do: inspect(run_id)

  defp triple({subject, predicate, object}) do
    "<#{escape_iri(subject)}> <#{escape_iri(predicate)}> #{object(object)} .\n"
  end

  defp object({:iri, iri}), do: "<#{escape_iri(iri)}>"
  defp object({:literal, value}), do: ~s("#{escape_literal(value)}")

  defp object({:typed, value, datatype}),
    do: ~s("#{escape_literal(value)}"^^<#{escape_iri(datatype)}>)

  # N-Triples IRIREF excludes #x00-#x20, <, >, ", {, }, |, ^, ` and \\ even
  # in escaped form, so those bytes (plus DEL and, for a binary that is not
  # valid UTF-8, every non-ASCII byte) are percent-encoded. A well-formed IRI
  # passes through unchanged.
  defp escape_iri(iri) do
    utf8? = String.valid?(iri)

    for <<byte <- iri>>, into: "" do
      if iri_byte_admitted?(byte, utf8?), do: <<byte>>, else: percent(byte)
    end
  end

  defp iri_byte_admitted?(byte, _utf8?) when byte <= 0x20 or byte == 0x7F, do: false
  defp iri_byte_admitted?(byte, _utf8?) when byte in ~c[<>"{}|^`\\], do: false
  defp iri_byte_admitted?(byte, utf8?) when byte >= 0x80, do: utf8?
  defp iri_byte_admitted?(_byte, _utf8?), do: true

  defp percent(byte), do: "%" <> Base.encode16(<<byte>>)

  # STRING_LITERAL_QUOTE excludes ", \\, LF and CR; every other control
  # character is also escaped so a literal is always one printable line.
  defp escape_literal(value) do
    for <<char::utf8 <- value>>, into: "" do
      escape_char(char)
    end
  end

  defp escape_char(?\\), do: "\\\\"
  defp escape_char(?"), do: ~s(\\")
  defp escape_char(?\n), do: "\\n"
  defp escape_char(?\r), do: "\\r"
  defp escape_char(?\t), do: "\\t"

  defp escape_char(char) when char < 0x20 or char == 0x7F do
    "\\u" <> String.pad_leading(Integer.to_string(char, 16), 4, "0")
  end

  defp escape_char(char), do: <<char::utf8>>

  @doc false
  def observe(plan_iri, run_id, outcome, started_at, started_mono) do
    finished_at = DateTime.utc_now()
    duration_us = System.monotonic_time(:microsecond) - started_mono

    %__MODULE__{
      plan_iri: plan_iri,
      run_id: run_id,
      status: status(outcome),
      started_at: started_at,
      finished_at: finished_at,
      duration_us: max(duration_us, 0),
      outcome_digest: digest(outcome)
    }
  end

  defp status({:ok, _result}), do: :succeeded
  defp status({:ok, _result, _reactor}), do: :succeeded
  defp status({:halted, _reactor}), do: :halted
  defp status({:error, _reason}), do: :failed

  # An outcome shape Reactor has not been observed to return is reported as
  # unknown rather than asserted to be a failure.
  defp status(_outcome), do: :unknown

  defp digest({:ok, result}), do: hash({:ok, result})
  defp digest({:ok, result, _reactor}), do: hash({:ok, result})

  defp digest({:halted, reactor}) do
    # The completed results are the substance of a halt: two halts that reached
    # the same steps with different values are different observations. A halt
    # whose reactor does not expose those fields falls back to a structural
    # digest rather than crashing: observation is total.
    completed =
      case safe_intermediate_results(reactor) do
        :invalid ->
          []

        results when is_map(results) ->
          results
          |> Enum.sort_by(&elem(&1, 0))
          |> Enum.map(fn {step, result} -> {canonical(step), canonical(result)} end)
      end

    hash({:halted, halt_state(reactor), completed})
  end

  defp safe_intermediate_results(reactor) when is_map(reactor),
    do: Map.get(reactor, :intermediate_results, %{})

  defp safe_intermediate_results(_reactor), do: :invalid

  defp halt_state(reactor) when is_map(reactor), do: Map.get(reactor, :state)
  defp halt_state(reactor), do: inspect(reactor, limit: :infinity)

  defp digest({:error, reason}), do: hash({:error, failure_identity(reason)})
  defp digest(other), do: hash({:unknown, inspect(other, limit: :infinity)})

  # A Reactor error embeds the failing step -- including its `make_ref/0`
  # reference -- and a stacktrace, so hashing the error term (or its inspect
  # rendering) gives two occurrences of the same failure two different content
  # addresses. Canonicalising replaces the terms that cannot repeat and drops
  # the stacktrace, keeping everything that actually identifies the failure.
  defp failure_identity(reason), do: canonical(reason)

  defp canonical(value) when is_reference(value), do: :"$reference"
  defp canonical(value) when is_pid(value), do: :"$pid"
  defp canonical(value) when is_port(value), do: :"$port"
  defp canonical(value) when is_function(value), do: :"$function"

  defp canonical(%{__struct__: module} = struct) do
    fields =
      struct
      |> Map.from_struct()
      |> Map.drop([:stacktrace])
      |> canonical()

    {module, fields}
  end

  defp canonical(value) when is_map(value) do
    value
    |> Map.to_list()
    |> Enum.sort()
    |> Enum.map(fn {key, field} -> {canonical(key), canonical(field)} end)
  end

  defp canonical(value) when is_list(value), do: Enum.map(value, &canonical/1)

  defp canonical(value) when is_tuple(value) do
    value |> Tuple.to_list() |> Enum.map(&canonical/1) |> List.to_tuple()
  end

  defp canonical(value), do: value

  defp hash(term) do
    term
    |> :erlang.term_to_binary([:deterministic])
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end
end
