# GENERATED by ggen_igniter from packs/tokyo-depeg-burn-in-pack/ontology.ttl (stage actuation_receipt).
# Do not render-verify this file in isolation; compile under the consumer project.
# Do not edit. Re-render with mix ggen_igniter.sync --pack-dir.
defmodule AshPPlan.TokyoDepeg.Stage.ActuationReceipt do
  @moduledoc """
  Generated stage handler for the `actuation_receipt` stage: Receipt: affidavit assemble/verify 5-field receipt per refusal; admitted policies replay and actuate with authority :none.

  Anti-vacuity contract: the deviation "tampered receipt verifies" MUST be detected --
  honest traffic passes this stage and the mutant fires
  `REFUSED_LEASE_EXPIRED` with a receipt subject.
  """

  @spec actuate_receipt(map()) :: {:ok, map()} | {:refused, atom(), map()}
  def actuate_receipt(scenario) do
    case check(scenario) do
      :ok ->
        {:ok, scenario}

      {:refused, reason} ->
        {:refused, reason, %{stage: "actuation_receipt", refusal_class: "REFUSED_LEASE_EXPIRED"}}
    end
  end

  @doc "Overridable seam: the consumer replaces this with the real production check."
  @spec check(map()) :: :ok | {:refused, atom()}
  def check(scenario), do: apply(__MODULE__, :check_impl, [scenario])

  @doc false
  @spec check_impl(map()) :: :ok | {:refused, atom()}
  def check_impl(_scenario), do: :ok
end
