# GENERATED by ggen_igniter from packs/tokyo-depeg-burn-in-pack/ontology.ttl (stage fencing).
# Do not render-verify this file in isolation; compile under the consumer project.
# Do not edit. Re-render with mix ggen_igniter.sync --pack-dir.
defmodule AshPPlan.TokyoDepeg.Stage.Fencing do
  @moduledoc """
  Generated stage handler for the `fencing` stage: Fencing: concurrent duplicate barrage; claim-CAS exactly-once; duplicates replay prior evidence.

  Anti-vacuity contract: the deviation "duplicate accepted as fresh execution" MUST be detected --
  honest traffic passes this stage and the mutant fires
  `REFUSED_DUPLICATE_EFFECT` with a receipt subject.
  """

  @spec fence_duplicates(map()) :: {:ok, map()} | {:refused, atom(), map()}
  def fence_duplicates(scenario) do
    case check(scenario) do
      :ok ->
        {:ok, scenario}

      {:refused, reason} ->
        {:refused, reason, %{stage: "fencing", refusal_class: "REFUSED_DUPLICATE_EFFECT"}}
    end
  end

  @doc "Overridable seam: the consumer replaces this with the real production check."
  @spec check(map()) :: :ok | {:refused, atom()}
  def check(scenario), do: apply(__MODULE__, :check_impl, [scenario])

  @doc false
  @spec check_impl(map()) :: :ok | {:refused, atom()}
  def check_impl(_scenario), do: :ok
end
