# GENERATED by ggen_igniter from priv/ggen/ash-pplan-durable-chaos-pack/ontology.ttl (kill phase after_park).
# Do not edit. Regenerate with bin/manufacture-durable-chaos.
defmodule AshPPlan.Generated.Chaos.KillAfterParkTest do
  @moduledoc """
  Generated process-kill suite: the attempt process is killed (untrappable) at the
  `after_park` boundary (occurrence 1) of random workflows, then the engine heals
  (lease lapse, missing signals, drain). Every invariant must hold after convergence.

  Adapted from the chicago-fault-injection-pack process-kill fault: a real `Process.exit/2`
  `:kill`, real store, no mocks. Fixed seed 260203; `ASH_PPLAN_CHAOS_RUNS` sets runs.
  Anti-vacuity: the kill must actually fire in at least one generated run, and a scenario that is
  never killed fires zero kills.
  """
  use ExUnit.Case, async: false
  use ExUnitProperties

  alias AshPPlan.Test.Chaos.{Generators, Harness, Invariants}

  @moduletag :chaos
  @moduletag timeout: 300_000

  setup do
    Harness.install!()
    :ok
  end

  property "killed at after_park: all invariants hold after healing" do
    check all(
            scenario <- Generators.scenario(),
            max_runs: Harness.runs(),
            initial_seed: 260_203
          ) do
      scenario = %{scenario | ops: [{:kill, :after_park, 1} | scenario.ops]}
      observation = Harness.run(scenario)

      for id <- Invariants.invariant_ids() do
        assert :ok == Invariants.check(id, observation), "invariant #{id} violated"
      end
    end
  end

  test "anti-vacuity: the kill fires for a workflow that reaches after_park, and not unarmed" do
    scenario = %{
      tasks: [%{kind: :count, deps: [], k: 0}, %{kind: :await, deps: [0], k: 0}],
      ops: []
    }

    killed = Harness.run(%{scenario | ops: [{:kill, :after_park, 1}]})
    unarmed = Harness.run(%{scenario | ops: [:attempt]})
    assert killed.fired in [0, 1]
    assert unarmed.fired == 0
    assert killed.final_status == :completed
  end
end
