# GENERATED by ggen_igniter from priv/ggen/ash-pplan-durable-chaos-pack/ontology.ttl (invariant standing_unique).
# Do not edit. Regenerate with bin/manufacture-durable-chaos.
defmodule AshPPlan.Chaos.StandingUniquePropertyTest do
  @moduledoc """
  Generated model-based chaos property: the standing ledger holds no duplicate keys.

  Random workflows (a DAG of 1-8 counting/Await/Poll steps), random kill points, signal orders
  (early, late, duplicate), clock jumps and cancels run against the real durable engine; after
  `Testing.drain` the observation must satisfy `Invariants.check(:standing_unique, _)`.

  The property starts from the recorded fixed seed 260105 (`initial_seed`), so a failure
  reproduces exactly; `ASH_PPLAN_CHAOS_RUNS` sets the run count. Anti-vacuity: the sabotage test
  feeds the check an observation corrupted to violate the invariant and requires it to fail.
  """
  use ExUnit.Case, async: false
  use ExUnitProperties

  alias AshPPlan.Test.Chaos.{Generators, Harness, Invariants}

  @moduletag :chaos
  @moduletag timeout: 300_000

  setup do
    Harness.install!()
    :ok
  end

  property "the standing ledger holds no duplicate keys" do
    check all(scenario <- Generators.scenario(), max_runs: Harness.runs(), initial_seed: 260_105) do
      assert :ok == Invariants.check(:standing_unique, Harness.run(scenario))
    end
  end

  test "anti-vacuity: the check refuses a sabotaged observation" do
    good = Harness.run(%{tasks: [%{kind: :count, deps: [], k: 0}], ops: [:attempt]})
    assert :ok == Invariants.check(:standing_unique, good)

    assert {:error, _} =
             Invariants.check(
               :standing_unique,
               AshPPlan.Test.Chaos.Sabotage.violate(:standing_unique, good)
             )
  end
end
