PREFIX ap: <https://w3id.org/ash-pplan#>
SELECT DISTINCT ?module ?name ?order WHERE {
  ?ext a ap:DslExtension ;
       ap:dslModule ?module ;
       ap:dslVerifier ?v .
  ?v ap:name ?name ; ap:order ?order .
}
ORDER BY ?order
