defmodule AshPPlan.Workflow.SelfhostClosureTest do
  @moduledoc """
  Self-hosting fixed point court: an UltraCode-style closure loop (observe, select, execute,
  integrate, verify) whose graph is itself an `ap:Workflow` (`selfhost` in `examples.ttl`,
  generated by `bin/manufacture-examples`) runs on the native durable engine and closes its own
  completion graph.

  Real Reactor, real ETS store, real OTP processes, a deterministic local agent under the
  `:construct` ceiling. The runner is killed at the integration gate of every iteration and the
  driver itself is replaced mid-loop; a fresh process resumes from the store and the frontier.

  Court: an unattended run ends with an empty frontier, each item executed exactly once, and a
  standing receipt naming the loop-closure order. Falsifier: an agent attempting DO authority is
  refused and the run loses standing. Anti-vacuity: a restart that ignores the store re-executes
  items and loses standing; a doubled execution loses standing; a refused loop has open items.
  """
  use ExUnit.Case, async: false

  # Registered at file load, before any test (including the generated provider courts) runs.
  AshPPlan.Examples.Selfhost.Adapter.register!()

  alias AshPPlan.Examples.Selfhost.{Adapter, Frontier, Steps}
  alias AshPPlan.Examples.Selfhost.Loop
  alias AshPPlan.Reactor.Durable.{Clock, Testing}
  alias AshPPlan.Reactor.Durable.Store.Ets

  @items [:observe, :select, :execute, :integration_gate, :integrate, :verify, :record_standing]

  setup do
    Adapter.install!()
    Clock.use_test_clock()
    on_exit(&Clock.reset/0)
    {:ok, store} = Ets.start_link()
    {:ok, store: store}
  end

  defp start_frontier(opts \\ []) do
    start_supervised!(%{
      id: Frontier,
      start: {Frontier, :start_link, [Loop.workflow().model(), opts]}
    })
  end

  test "the frontier is the loop's own completion graph" do
    start_frontier()
    assert Enum.sort(Enum.map(Frontier.items(), & &1.id)) == Enum.sort(@items)
    assert Enum.sort(Frontier.open()) == Enum.sort(@items)

    assert Enum.all?(Loop.bindings(), fn {_task, r} ->
             r.binding.adapter in [:selfhost, :durable]
           end)
  end

  test "unattended loop with a mid-loop driver kill ends with an empty frontier, once each", %{
    store: store
  } do
    start_frontier()

    # iteration 1 parks at the gate (runner killed), then completes under a fresh runner
    assert {:parked, "selfhost-1"} = Loop.advance(store)
    assert Frontier.executions() == %{observe: 1}
    assert length(Testing.tape(store, "selfhost-1")) == 3
    assert {:completed, "selfhost-1"} = Loop.advance(store)
    # iteration 2 parks; the whole driver process is abandoned here
    assert {:parked, "selfhost-2"} = Loop.advance(store)

    # a different process resumes the in-flight run and drives the loop to closure
    assert :closed = Task.async(fn -> Loop.run(store) end) |> Task.await(60_000)

    assert Frontier.open() == []
    assert Frontier.executions() == Map.new(@items, &{&1, 1})

    receipt = Loop.receipt(store)
    assert receipt.standing == :standing
    assert receipt.broken_term == nil
    assert receipt.loop_closure_order == Steps.closure_order()
    assert receipt.loop_closure_order == "LOOP-CLOSURE-26.10.1-SELFHOST"
    assert receipt.authority == %{ceiling: :construct, do_granted: false}
    assert length(receipt.identity.runs) == 7
    assert Enum.all?(Map.values(receipt.replay.statuses), &(&1 == :completed))

    assert Enum.all?(Map.values(receipt.replay.run_receipts), fn r ->
             r.standing == :standing and r.loop_closure_order == Steps.closure_order() and
               r.authority.ceiling == :construct and r.authority.granted != :do
           end)

    assert map_size(receipt.replay.run_receipts) == 7
    # a closed loop stays closed: nothing re-executes
    assert Loop.advance(store) == :closed
    assert Frontier.executions() == Map.new(@items, &{&1, 1})
  end

  test "falsifier: an agent attempting DO authority is refused and the run loses standing", %{
    store: store
  } do
    start_frontier(request_authority: %{integrate: :do})

    assert {:failed, run_id, reason} = Loop.run(store)
    assert run_id == "selfhost-5"
    assert reason.status != :completed

    refute Map.has_key?(Frontier.receipts(), run_id)
    refute Map.has_key?(Frontier.executions(), :integrate)
    assert %{status: :refused} = Frontier.item(:integrate)
    assert :integrate in Frontier.open()

    receipt = Loop.receipt(store)
    assert receipt.standing == :lost
    assert receipt.broken_term == :authority_refused
    assert receipt.authority.do_granted == false
    assert receipt.consequence.refused == [:integrate]
    # the four iterations before the refusal keep their own standing receipts
    assert map_size(receipt.replay.run_receipts) == 4
    # a refused loop does not restart the refused item
    assert Loop.advance(store) == :closed
    assert Frontier.executions() == Map.new(Enum.take(@items, 4), &{&1, 1})
  end

  test "anti-vacuity: a restart that ignores the store re-executes items and loses standing", %{
    store: store
  } do
    start_frontier()
    assert {:parked, _} = Loop.advance(store)
    {:completed, _} = Loop.advance(store)

    # restart ignoring the ledger: fresh store, frontier reopened -> observe executes twice
    {:ok, fresh} = Ets.start_link()
    assert {:parked, _} = Loop.advance(fresh)
    assert Loop.advance(fresh) == {:completed, "selfhost-1"}
    :ok = Frontier.executed(:observe, %{digest: "x", authority: :construct})
    assert Frontier.executions().observe == 2

    assert Loop.run(store) == :closed
    receipt = Loop.receipt(store)
    assert receipt.standing == :lost
    assert receipt.broken_term == :item_not_executed_once
  end

  test "anti-vacuity: the receipt without a closed frontier carries no standing", %{store: store} do
    start_frontier()
    assert {:parked, _} = Loop.advance(store)
    receipt = Loop.receipt(store)
    assert receipt.standing == :lost
    assert receipt.broken_term == :frontier_not_empty
  end
end
