# GENERATED by ggen_igniter from packs/tokyo-depeg-burn-in-pack/ontology.ttl. Do not edit.
# Required trade lifecycle as data (Van der Aalst conformance model):
# RiskPreflight -> CollateralCheck -> SanctionsScreen -> Execution.
# Execution is reachable ONLY through SanctionsScreen; the sanctions-skip
# mutant must align at cost > 0. Honest traces align at cost 0.
[
  places: [
    %{id: :risk_preflight, label: "RiskPreflight", guard: nil},
    %{id: :collateral_check, label: "CollateralCheck", guard: nil},
    %{id: :sanctions_screen, label: "SanctionsScreen", guard: nil},
    %{id: :execution, label: "Execution", guard: :SanctionsScreen}
  ],
  transitions: [:risk_to_collateral, :collateral_to_sanctions, :sanctions_to_execution],
  arcs: [
    {:CollateralCheck, :collateral_to_sanctions, :SanctionsScreen},
    {:RiskPreflight, :risk_to_collateral, :CollateralCheck},
    {:SanctionsScreen, :sanctions_to_execution, :Execution}
  ],
  effect_invariants: [
    %{
      id: :blake3_over_jcs,
      expr: "effect_identity = BLAKE3(JCS_canonical(order_payload))",
      kind: :hash
    },
    %{
      id: :unique_effect_instance,
      expr:
        "one effect_instance_id per accepted mutation; duplicates replay prior evidence, never re-execute",
      kind: :uniqueness
    }
  ],
  refusal_classes: [
    REFUSED_AUTHORITY_REVOKED: "tokyo.authority_revoked",
    REFUSED_CONFORMANCE_DEVIATION: "tokyo.conformance_deviation",
    REFUSED_DUPLICATE_EFFECT: "tokyo.duplicate_effect",
    REFUSED_LEASE_EXPIRED: "tokyo.lease_expired",
    REFUSED_NO_SUCH_RUN: "tokyo.no_such_run",
    missing_domain: "tokyo.sa2a.missing_domain",
    missing_initial: "tokyo.sa2a.missing_initial",
    missing_plan_iri: "tokyo.sa2a.missing_plan_iri",
    missing_subject: "tokyo.sa2a.missing_subject",
    plan_not_found: "tokyo.sa2a.plan_not_found",
    planner_refused: "tokyo.sa2a.planner_refused",
    unsupported_formalism: "tokyo.sa2a.unsupported_formalism"
  ]
]
